### ISSUE TITLE
Mod installation issue

### ISSUE THREAD

**Issue by Lunaraia** [NiceneNerd/BCML#101]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 121, in worker
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 44, in mapstar
  File "D:\bcml\pkgs\bcml\mergers\texts.py", line 267, in merge_msyt
    out.write_text(json.dumps(text_data, ensure_ascii=False))
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pathlib.py", line 1236, in write_text
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4982-4995: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\bcml\pkgs\bcml\install.py", line 561, in refresh_merges
    merger.perform_merge()
  File "D:\bcml\pkgs\bcml\util.py", line 461, in timed_function
    res = func(*args, **kwargs)
  File "D:\bcml\pkgs\bcml\mergers\texts.py", line 432, in perform_merge
    this_pool.map(partial(merge_msyt, tmp_dir=tmp_dir), diffs[lang].items())
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 268, in map
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 657, in get
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4982-4995: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bcml\pkgs\bcml\_api.py", line 30, in status_run
    data = func(*args, **kwargs)
  File "D:\bcml\pkgs\bcml\install.py", line 271, in do_and_refresh
    res = func(*args, **kwargs)
  File "D:\bcml\pkgs\bcml\_api.py", line 466, in remerge
    f"There was an error merging your mods. {str(err)}\n"
Exception: There was an error merging your mods. 'charmap' codec can't encode characters in position 4982-4995: character maps to <undefined>
Note that this could leave your game in an unplayable state.

I have no idea what this error means, but it's preventing my mods from even being installed or run at all, all I wanted was to re-emerge the mods to fix a graphical issue I was having and that happened.

**Comment by NiceneNerd** [comment]
It's already fixed as of 7b5ea160612217f14c481ea277f4743ee060877f, but I haven't made a new release yet because I'm redoing the installer. It's possible to fix Windows in the meantime by setting Windows to use UTF-8 by default: Control Panel -> Clock and Region -> Change time, date, or number formats -> Administrative -> Change system locale -> (Beta) Use Unicode UTF-8 for worldwide language support.
