### ISSUE TITLE
Another Issue

### ISSUE THREAD

**Issue by Lunaraia** [NiceneNerd/BCML#102]
Since II have no idea if it's related to the other issue, I thought it's best to report it, just in case.

Traceback (most recent call last):
  File "D:\BCML\pkgs\bcml\install.py", line 300, in install_mod
    tmp_dir = open_mod(mod)
  File "D:\BCML\pkgs\bcml\install.py", line 68, in open_mod
    raise Exception("No files were extracted.")
Exception: No files were extracted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\BCML\pkgs\bcml\_api.py", line 30, in status_run
    data = func(*args, **kwargs)
  File "D:\BCML\pkgs\bcml\install.py", line 271, in do_and_refresh
    res = func(*args, **kwargs)
  File "D:\BCML\pkgs\bcml\_api.py", line 302, in install_mod
    for m in params["mods"]
  File "D:\BCML\pkgs\bcml\_api.py", line 302, in <listcomp>
    for m in params["mods"]
  File "D:\BCML\pkgs\bcml\install.py", line 317, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. No files were extracted.
Your mod is being removed, and no changes have been made.

I did as you suggested in the other issue I posted and turned on the UTF-8 unicode. But this particular error popped up when I tried to redownload the Linkle Mod as I uninstalled it to see if that was the issue of the prior one. No idea if the errors are related as code like this might as well be an alien language to me.

**Comment by NiceneNerd** [comment]
This _usually_ happens when something has gone wrong on GameBanana. Directions to find out exactly whether or why this is the case, however, would be a bit difficult to follow. If you want to try I'll tell you how, though.

**Comment by Lunaraia** [comment]
nah it's fine I guess it will be fixed eventually, probably just another server hiccup on gamebanana's side
