### ISSUE TITLE
Unable to launch BCML through shortcut or Command Prompt

### ISSUE THREAD

**Issue by floral-qua-floral** [NiceneNerd/BCML#118]
I'm now able to install BCML without any Windows Security issues, which is great - however it seems there's still something preventing BCML from opening properly. I've gone and uninstalled/reinstalled, but it doesn't seem to have any effect on the issue. I've also made sure I have the VC distributable linked to on BCML's gamebanana page, and restarted my computer just in case, but no luck there either.

Clicking the Start Menu shortcut does not cause any window to appear, however it does add two instances of Python.exe to the task manager, one of which goes away after a few seconds. The other appears to run indefinitely in the background until I kill the process myself. Interestingly, if I navigate to the installation directory and run `python.exe -m bcml` (as directed in #114), it does _not_ cause Python to appear in the task manager at all. Instead, it outputs the following:
```
C:\Games\BCML 3.3.2>python.exe -m bcml

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Games\BCML 3.3.2\Lib\site-packages\Python.Runtime.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at clrModule.PyInit_clr()
```

**Comment by NiceneNerd** [comment]
This is a duplicate of #116. Download the new `setup.exe` from [here](https://github.com/NiceneNerd/bcml-installer/releases/download/v0.1.2/setup.exe), replace the existing one, and run the new one.
