### ISSUE TITLE
First-time setup Wizard does nothing

### ISSUE THREAD

**Issue by ripps818** [NiceneNerd/BCML#120]
When I first use BCML, I get this:
```
Traceback (most recent call last):
  File "G:\Program Files\bcml-win64-bundle\Lib\site-packages\bcml\_api.py", line 31, in status_run
    data = func(*args, **kwargs)
  File "G:\Program Files\bcml-win64-bundle\Lib\site-packages\bcml\_api.py", line 75, in sanity_check
    util.sanity_check()
  File "G:\Program Files\bcml-win64-bundle\Lib\site-packages\bcml\util.py", line 489, in sanity_check
    get_game_dir()
  File "G:\Program Files\bcml-win64-bundle\Lib\site-packages\bcml\util.py", line 650, in get_game_dir
    "The BOTW game dump directory has not been set or does not exist."
FileNotFoundError: The BOTW game dump directory has not been set or does not exist.

```
and then 5 seconds later it closes the app and starts a first time wizard. The problem is, it doesn't do anything. It opens, says that I can't import any settings, and then it leads me to a "Welcome to BCML" page with only a back arrow and and save icon that doesn't do anything.

**Comment by ripps818** [comment]
Ok, I seemed to have fixed this by renaming the BCML folder in AppData and letting it create a new config folder.
