### ISSUE TITLE
Mods wont install for Switch config

### ISSUE THREAD

**Issue by FreepDryer** [NiceneNerd/BCML#129]
`Traceback (most recent call last):
  File "D:\Chrome downloads\bcml-win64-bundle_365ae\Lib\site-packages\bcml\install.py", line 387, in install_mod
    f'"{mod_name}" is for {friendly_plaform(rules["platform"])}, not '
ValueError: "Ultimate Fierce Deity Sword" is for Switch, not  Switch.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Chrome downloads\bcml-win64-bundle_365ae\Lib\site-packages\bcml\_api.py", line 31, in status_run
    data = func(*args, **kwargs)
  File "D:\Chrome downloads\bcml-win64-bundle_365ae\Lib\site-packages\bcml\install.py", line 307, in do_and_refresh
    res = func(*args, **kwargs)
  File "D:\Chrome downloads\bcml-win64-bundle_365ae\Lib\site-packages\bcml\_api.py", line 314, in install_mod
    for m in params["mods"]
  File "D:\Chrome downloads\bcml-win64-bundle_365ae\Lib\site-packages\bcml\_api.py", line 314, in <listcomp>
    for m in params["mods"]
  File "D:\Chrome downloads\bcml-win64-bundle_365ae\Lib\site-packages\bcml\install.py", line 410, in install_mod
    raise util.InstallError(err, name) from err
bcml.util.InstallError: An error occured when installing Ultimate Fierce Deity Sword. "Ultimate Fierce Deity Sword" is for Switch, not  Switch.'
Your mod is being removed, and no changes have been made.
`
Attempting to install any mod, either from bcml itself or gamebanana, and using that downloaded file to install, it always comes with the same error, "<ModName> is for Switch, not Switch."
Restarting the application or using different mods produces the same error.

**Comment by NiceneNerd** [comment]
Are  you sure it happens for any mod? It should happen to several of Shadow Dragon's mods because they were made with an old beta version of BCML 3, but I can't replicate it with anything else.

**Comment by FreepDryer** [comment]
You are correct, now that you point it out only a few mods dont work as planned. I tried it out with other mods and it's all good, user error I suppose, but thanks for the quick response!
