### ISSUE TITLE
ssl error with gamebanana?

### ISSUE THREAD

**Issue by AeliusSaionji** [NiceneNerd/BCML#130]
gamabanana tab doesn't load any images, and this error happens when trying to install:

```python
Traceback (most recent call last):
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\urllib3\connection.py", line 371, in connect
    ssl_context=context,
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ssl.py", line 423, in wrap_socket
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ssl.py", line 870, in _create
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\urllib3\connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gamebanana.com', port=443): Max retries exceeded with url: /dl/517877 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\aelius\Downloads\bcml-win64-bundle\Lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='gamebanana.com', port=443): Max retries exceeded with url: /dl/517877 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
```

**Comment by NiceneNerd** [comment]
It's a GameBanana server issue, nothing to be done on BCML's end.
