### ISSUE TITLE
Error with extracting RAR on Linux

### ISSUE THREAD

**Issue by Dokthoror** [NiceneNerd/BCML#134]
Hi, I'm using Pop!OS 20.10 and I have this error while installing the Zelda's Ballad mod with the shield_fix.rar file : 
```
Traceback (most recent call last):
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/install.py", line 114, in open_mod
    upgrade.convert_old_mod(rulesdir, delete_old=True)
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/upgrade.py", line 45, in convert_old_mod
    rules_to_info(mod / "rules.txt", delete_old=delete_old)
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/upgrade.py", line 103, in rules_to_info
    info = parse_rules(rules_path)
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/upgrade.py", line 82, in parse_rules
    "name": str(rules["Definition"]["name"]).strip("\"' "),
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Definition'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/_api.py", line 31, in status_run
    data = func(*args, **kwargs)
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/install.py", line 307, in do_and_refresh
    res = func(*args, **kwargs)
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/_api.py", line 307, in install_mod
    mods = [
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/_api.py", line 308, in <listcomp>
    install.install_mod(
  File "/home/pascal/.local/lib/python3.8/site-packages/bcml/install.py", line 353, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. 'Definition'
Your mod is being removed, and no changes have been made.
```
I don't know how to fix this because I don't know Python language. I used to be on Windows, but since I went to Linux, it didn't work anymore.
I aalready checked this : https://github.com/NiceneNerd/BCML/issues/87 but found nothing helping me.

**Comment by NiceneNerd** [comment]
As far as I can tell, some rare RAR files aren't supported by p7zip on Linux, which is what BCML uses. There's no way around that for BCML itself, but you can always use a different tool (e.g. `unrar`) to extract it before installing it with BCML.
