### ISSUE TITLE
BCML can't install mods. Says no files were extracted.

### ISSUE THREAD

**Issue by DanZC** [NiceneNerd/BCML#136]
I installed BCML using pip. Whenever I install a mod, this error shows up:

```
Traceback (most recent call last):
  File "c:\users\dan\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 336, in install_mod
    tmp_dir = open_mod(mod)
  File "c:\users\dan\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 94, in open_mod
    raise Exception("No files were extracted.")
Exception: No files were extracted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\dan\appdata\local\programs\python\python37\lib\site-packages\bcml\_api.py", line 31, in status_run
    data = func(*args, **kwargs)
  File "c:\users\dan\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 307, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\dan\appdata\local\programs\python\python37\lib\site-packages\bcml\_api.py", line 314, in install_mod
    for m in params["mods"]
  File "c:\users\dan\appdata\local\programs\python\python37\lib\site-packages\bcml\_api.py", line 314, in <listcomp>
    for m in params["mods"]
  File "c:\users\dan\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 353, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. No files were extracted.
Your mod is being removed, and no changes have been made.
```

I've tried running the program as an administrator to see if that would help and same result.

**Comment by NiceneNerd** [comment]
GameBanana problem
