### ISSUE TITLE
error downloading files

### ISSUE THREAD

**Issue by Ducky183** [NiceneNerd/BCML#137]
Some mods seem to work fine. But others will go to the install screen almost instantly, too fast for it to have downloaded, then give an error message. I've tried reinstalling BCML with no luck.

Traceback (most recent call last):
  File "C:\Users\dairy\Desktop\mods\Breath of the Wild\BCML\Lib\site-packages\bcml\install.py", line 336, in install_mod
    tmp_dir = open_mod(mod)
  File "C:\Users\dairy\Desktop\mods\Breath of the Wild\BCML\Lib\site-packages\bcml\install.py", line 94, in open_mod
    raise Exception("No files were extracted.")
Exception: No files were extracted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dairy\Desktop\mods\Breath of the Wild\BCML\Lib\site-packages\bcml\_api.py", line 31, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\dairy\Desktop\mods\Breath of the Wild\BCML\Lib\site-packages\bcml\install.py", line 307, in do_and_refresh
    res = func(*args, **kwargs)
  File "C:\Users\dairy\Desktop\mods\Breath of the Wild\BCML\Lib\site-packages\bcml\_api.py", line 314, in install_mod
    for m in params["mods"]
  File "C:\Users\dairy\Desktop\mods\Breath of the Wild\BCML\Lib\site-packages\bcml\_api.py", line 314, in <listcomp>
    for m in params["mods"]
  File "C:\Users\dairy\Desktop\mods\Breath of the Wild\BCML\Lib\site-packages\bcml\install.py", line 353, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. No files were extracted.
Your mod is being removed, and no changes have been made.

**Comment by NiceneNerd** [comment]
It's GameBanana.

**Comment by Ducky183** [comment]
ah, my bad. will try again some other time then. thanks for the heads up
