### ISSUE TITLE
can't install any mod

### ISSUE THREAD

**Issue by KH1501** [NiceneNerd/BCML#141]
Traceback (most recent call last):
  File "C:\Users\aspik\AppData\Local\bcml\Python\lib\site-packages\bcml\_api.py", line 335, in install_mod
    install.refresh_merges()
  File "C:\Users\aspik\AppData\Local\bcml\Python\lib\site-packages\bcml\install.py", line 625, in refresh_merges
    merger.perform_merge()
  File "C:\Users\aspik\AppData\Local\bcml\Python\lib\site-packages\bcml\util.py", line 462, in timed_function
    res = func(*args, **kwargs)
  File "C:\Users\aspik\AppData\Local\bcml\Python\lib\site-packages\bcml\mergers\mubin.py", line 819, in perform_merge
    merge_dungeonstatic(self.consolidate_diffs(self.get_all_diffs()))
  File "C:\Users\aspik\AppData\Local\bcml\Python\lib\site-packages\bcml\mergers\mubin.py", line 453, in merge_dungeonstatic
    missing_ok=True
TypeError: unlink() got an unexpected keyword argument 'missing_ok'

Yesterday it still worked. Seems like the new update is to blame?

**Comment by NiceneNerd** [comment]
Turns out the `missing_ok` parameter was added in Python 3.8, so it won't with with 3.7. I'll remove it later today, but if you don't want to wait you can switch to 3.8.

**Comment by NiceneNerd** [comment]
Fixed in 3.4.4
