### ISSUE TITLE
Bcml wont launch after I install it from Gamebanana here's the debug file after I tried to launch it from cmd 

### ISSUE THREAD

**Issue by JustQuill** [NiceneNerd/BCML#159]
[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "e:\bcml\lib\site-packages\bcml\util.py", line 605, in get_settings
    settings.update(json.loads(settings_path.read_text()))
  File "e:\bcml\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "e:\bcml\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "e:\bcml\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\bcml\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\bcml\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\BCML\Scripts\bcml-debug.exe\__main__.py", line 7, in <module>
    sys.exit(main_debug())
  File "e:\bcml\lib\site-packages\bcml\__main__.py", line 144, in main_debug
    main(True)
  File "e:\bcml\lib\site-packages\bcml\__main__.py", line 94, in main
    configure_cef(debug)
  File "e:\bcml\lib\site-packages\bcml\__main__.py", line 50, in configure_cef
    cache = util.get_storage_dir() / "cef_cache"
  File "e:\bcml\lib\site-packages\bcml\util.py", line 534, in get_storage_dir
    folder = get_settings("store_dir")
  File "e:\bcml\lib\site-packages\bcml\util.py", line 622, in get_settings
    raise RuntimeError("BCML could not load its settings file") from err
RuntimeError: BCML could not load its settings file

**Comment by jordanbtucker** [comment]
It sounds like your `AppData\Local\bcml\settings.json` file is corrupt. I would move your `AppData\Local\bcml` folder to your desktop as a backup, then start BCML. (Make sure you've moved it and not just copied it.) This should reset BCML to default settings, so you'll have to configure your Cemu folders again, but at least it should start working again.

1. In Windows, click Start
2. Type `Run` and hit enter
3. Type `%LOCALAPPDATA%` and hit enter
4. Find the `bcml` folder and move it to your desktop
5. Start BCML

Once you've got BCML working again, you can delete the backup `bcml` folder on your desktop.
