### ISSUE TITLE
Error when installing BCML

### ISSUE THREAD

**Issue by DumbassTom** [NiceneNerd/BCML#168]
When I try to install BCML by typing 'pip install bcml' on the command prompt, it starts to install normally, but at the end i get an error. I got another error before telling me to install CMake and I did so, but now it gives me another error wich I have no idea how to fix.

`
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\tomuj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tomuj\\AppData\\Local\\Temp\\pip-install-9701k0gr\\syaz0_51f008cda23445079130be7dce5542c5\\setup.py'"'"'; __file__='"'"'C:\\Users\\tomuj\\AppData\\Local\\Temp\\pip-install-9701k0gr\\syaz0_51f008cda23445079130be7dce5542c5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tomuj\AppData\Local\Temp\pip-record-t81lk2mr\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\tomuj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\syaz0'
         cwd: C:\Users\tomuj\AppData\Local\Temp\pip-install-9701k0gr\syaz0_51f008cda23445079130be7dce5542c5\
    Complete output (65 lines):
    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py:463: UserWarning: Normalizing 'v1.0.1' to '1.0.1'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    running build_ext
    -- Building for: Visual Studio 16 2019
    -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18362.
    -- The CXX compiler identification is MSVC 19.29.30038.1
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: D:/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:10 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.

      Could not find a package configuration file provided by "pybind11" with any
      of the following names:

        pybind11Config.cmake
        pybind11-config.cmake

      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/tomuj/AppData/Local/Temp/pip-install-9701k0gr/syaz0_51f008cda23445079130be7dce5542c5/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tomuj\AppData\Local\Temp\pip-install-9701k0gr\syaz0_51f008cda23445079130be7dce5542c5\setup.py", line 72, in <module>
        setuptools.setup(
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\tomuj\AppData\Local\Temp\pip-install-9701k0gr\syaz0_51f008cda23445079130be7dce5542c5\setup.py", line 36, in run
        self.build_extension(ext)
      File "C:\Users\tomuj\AppData\Local\Temp\pip-install-9701k0gr\syaz0_51f008cda23445079130be7dce5542c5\setup.py", line 62, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\tomuj\\AppData\\Local\\Temp\\pip-install-9701k0gr\\syaz0_51f008cda23445079130be7dce5542c5\\src', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\tomuj\\AppData\\Local\\Temp\\pip-install-9701k0gr\\syaz0_51f008cda23445079130be7dce5542c5\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=C:\\Users\\tomuj\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\tomuj\\AppData\\Local\\Temp\\pip-install-9701k0gr\\syaz0_51f008cda23445079130be7dce5542c5\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\tomuj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tomuj\\AppData\\Local\\Temp\\pip-install-9701k0gr\\syaz0_51f008cda23445079130be7dce5542c5\\setup.py'"'"'; __file__='"'"'C:\\Users\\tomuj\\AppData\\Local\\Temp\\pip-install-9701k0gr\\syaz0_51f008cda23445079130be7dce5542c5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tomuj\AppData\Local\Temp\pip-record-t81lk2mr\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\tomuj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\syaz0' Check the logs for full command output.
`

**Comment by NiceneNerd** [comment]
You can't use Python 3.9, per the docs.
