### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Starcrater21** [NiceneNerd/BCML#177]
ERROR: Could not find a version that satisfies the requirement oead~=1.2.0 (from -r requirements.txt (line 8)) (from versions: none)
ERROR: No matching distribution found for oead~=1.2.0 (from -r requirements.txt (line 8))
getting this error when installing

**Comment by NiceneNerd** [comment]
You have the wrong Python version if you get such an error.

**Comment by Starcrater21** [comment]
3.8.10?

**Comment by Starcrater21** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\starc\appdata\local\programs\python\python37-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\starc\\AppData\\Local\\Temp\\pip-install-e4maxd1m\\syaz0_1ae1171476f6452683d1bfd93abe83d0\\setup.py'"'"'; __file__='"'"'C:\\Users\\starc\\AppData\\Local\\Temp\\pip-install-e4maxd1m\\syaz0_1ae1171476f6452683d1bfd93abe83d0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\starc\AppData\Local\Temp\pip-record-zomf56nl\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\starc\appdata\local\programs\python\python37-32\Include\syaz0'
         cwd: C:\Users\starc\AppData\Local\Temp\pip-install-e4maxd1m\syaz0_1ae1171476f6452683d1bfd93abe83d0\
    Complete output (51 lines):
    c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    c:\users\starc\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\dist.py:397: UserWarning: Normalizing 'v1.0.1' to '1.0.1'
      normalized_version,
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\starc\AppData\Local\Temp\pip-install-e4maxd1m\syaz0_1ae1171476f6452683d1bfd93abe83d0\setup.py", line 25, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\subprocess.py", line 376, in check_output
        **kwargs).stdout
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\subprocess.py", line 453, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1155, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\starc\AppData\Local\Temp\pip-install-e4maxd1m\syaz0_1ae1171476f6452683d1bfd93abe83d0\setup.py", line 92, in <module>
        zip_safe=False,
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\starc\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\starc\AppData\Local\Temp\pip-install-e4maxd1m\syaz0_1ae1171476f6452683d1bfd93abe83d0\setup.py", line 28, in run
        ", ".join(e.name for e in self.extensions))
    RuntimeError: CMake must be installed to build the following extensions: syaz0
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\starc\appdata\local\programs\python\python37-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\starc\\AppData\\Local\\Temp\\pip-install-e4maxd1m\\syaz0_1ae1171476f6452683d1bfd93abe83d0\\setup.py'"'"'; __file__='"'"'C:\\Users\\starc\\AppData\\Local\\Temp\\pip-install-e4maxd1m\\syaz0_1ae1171476f6452683d1bfd93abe83d0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\starc\AppData\Local\Temp\pip-record-zomf56nl\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\starc\appdata\local\programs\python\python37-32\Include\syaz0' Check the logs for full command output.
getting this error now

**Comment by NiceneNerd** [comment]
That's 32-bit Python.
