### ISSUE TITLE
Can't install any Mods

### ISSUE THREAD

**Issue by xSamukaBRx** [NiceneNerd/BCML#178]
Tried installing Second Wind + Eventide Fix
Resulted in this: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bcml/install.py", line 344, in install_mod
    tmp_dir = open_mod(mod)
  File "/usr/local/lib/python3.8/dist-packages/bcml/install.py", line 75, in open_mod
    x_args = [get_7z_path(), "x", str(path), f"-o{str(tmpdir)}"]
  File "/usr/local/lib/python3.8/dist-packages/bcml/util.py", line 1387, in get_7z_path
    os.chmod(bundle_path, 0o755)
PermissionError: [Errno 1] Operação não permitida: '/usr/local/lib/python3.8/dist-packages/bcml/helpers/7z'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bcml/_api.py", line 32, in status_run
    data = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/bcml/_api.py", line 394, in apply_queue
    install.install_mod(
  File "/usr/local/lib/python3.8/dist-packages/bcml/install.py", line 361, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. [Errno 1] Operação não permitida: '/usr/local/lib/python3.8/dist-packages/bcml/helpers/7z'
Your mod is being removed, and no changes have been made.
```

Linux Distro: Linux Mint 20.2 Uma
CEMU Version: 1.25.0b via Lutris

Tried installing each mod individually but it resulted in a loop on the "One Sec" screen (over 30min, and didn't install) with the following error on Terminal: 

`js: Uncaught (in promise) PermissionError: [Errno 1] Operação não permitida: '/usr/local/lib/python3.8/dist-packages/bcml/helpers/7z`

**I apologize for the excessive edits, my english is not perfect, so i'm trying to make my issue as clear as possible.**

**Comment by NiceneNerd** [comment]
Try using chmod on the 7z binary

**Comment by xSamukaBRx** [comment]
and how to i do that exactly? sorry to bother, i'm a total noob.
