### ISSUE TITLE
Can't Run Bcml

### ISSUE THREAD

**Issue by idkwhattoputasname** [NiceneNerd/BCML#181]
Hello I got an error from trying to run bcml and I don't know if I install it wrong or it's error on python

[2021-08-14 20:10:33] Traceback (most recent call last):

  File "\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 605, in get_settings

    settings.update(json.loads(settings_path.read_text()))

  File "\appdata\local\programs\python\python38\lib\json\__init__.py", line 357, in loads

    return _default_decoder.decode(s)

  File "\appdata\local\programs\python\python38\lib\json\decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "\appdata\local\programs\python\python38\lib\json\decoder.py", line 353, in raw_decode

    obj, end = self.scan_once(s, idx)

json.decoder.JSONDecodeError: Invalid \escape: line 9 column 22 (char 462)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "\AppData\Local\Programs\Python\Python38\Scripts\bcml.exe\__main__.py", line 7, in <module>

    sys.exit(main())

  File "\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 94, in main

    configure_cef(debug)

  File "\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 50, in configure_cef

    cache = util.get_storage_dir() / "cef_cache"

  File "\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 534, in get_storage_dir

    folder = get_settings("store_dir")

  File "\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 622, in get_settings

    raise RuntimeError("BCML could not load its settings file") from err

RuntimeError: BCML could not load its settings file

**Comment by NiceneNerd** [comment]
Your BCML settings file is broken. It's probably at `%LOCALAPPDATA%\bcml\settings.json`, post it here.
