### ISSUE TITLE
installing BCML aborts midway

### ISSUE THREAD

**Issue by ahegaosensei** [NiceneNerd/BCML#183]
Attempting to install BCML using `pip install bcml` aborts during "running setup.py install for syaz0" with the following output:

```
   Running setup.py install for syaz0 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ci60dja5\\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ci60dja5\\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-4_672817\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\Include\syaz0'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-ci60dja5\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\
    Complete output (49 lines):
    c:\python\lib\site-packages\setuptools\dist.py:463: UserWarning: Normalizing 'v1.0.1' to '1.0.1'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\Temp\pip-install-ci60dja5\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\setup.py", line 25, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "c:\python\lib\subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "c:\python\lib\subprocess.py", line 505, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\python\lib\subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\python\lib\subprocess.py", line 1420, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified`

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-ci60dja5\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\setup.py", line 72, in <module>
        setuptools.setup(
      File "c:\python\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\User\AppData\Local\Temp\pip-install-ci60dja5\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\setup.py", line 27, in run
        raise RuntimeError("CMake must be installed to build the following extensions: " +
    RuntimeError: CMake must be installed to build the following extensions: syaz0
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ci60dja5\\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ci60dja5\\syaz0_cd2fc1711dd84e24ac4a2deee055c2cf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-4_672817\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\Include\syaz0' Check the logs for full command output.
```

Have latest python and pip versions, properly set to PATH. Running win10 64-bit with the appropriate python, using an elevated command prompt, etc. any ideas?

**Comment by NiceneNerd** [comment]
What version of Python is it, exactly?

**Comment by ahegaosensei** [comment]
Latest release, 3.9.6 - I think that might actually be the problem, I was looking around elsewhere and it looks like syaz0 is deprecated after 3.8.
