### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dgyfgbmc/pyqtwebengine/

### ISSUE THREAD

**Issue by treypop** [NiceneNerd/BCML#188]
``` Collecting bcml
  Downloading https://files.pythonhosted.org/packages/ee/f6/ad3289e893826c2938b06ceb6e825b13777a6e633e7078f3c15f8b010516/bcml-3.5.0-py3-none-any.whl (29.1MB)
    100% |████████████████████████████████| 29.1MB 11kB/s 
Collecting byml~=2.3.1 (from bcml)
  Downloading https://files.pythonhosted.org/packages/c7/c7/9cb0484c3ea1b52540c5b1916022baba9265a19b19077a4e3f28d48297f6/byml-2.3.1-py3-none-any.whl
Collecting requests~=2.23.0 (from bcml)
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 738kB/s 
Collecting pyqtwebengine~=5.15.2; platform_system == "Linux" (from bcml)
  Downloading https://files.pythonhosted.org/packages/fb/5d/4c5bb7adca4f2436545a391fe311dcb4ccc711f1ce2ab7adb87475ec566e/PyQtWebEngine-5.15.4.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 2.2MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-dgyfgbmc/pyqtwebengine/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dgyfgbmc/pyqtwebengine/ ```



How do I fix this?

**Comment by NiceneNerd** [comment]
What distro do you have? Try installing `PyQtWebEngine` from its repos instead of pip.

**Comment by treypop** [comment]
Python 3.7.3 on Debian

**Comment by NiceneNerd** [comment]
...Did you try my suggestion?

**Comment by t3nk3y** [comment]
Trey, once I had a working Py 3.7 environment, I was able to get things going by using the python virtual environments.

`
python3 -m venv /path/to/new/virtual/environment
cd /path/to/new/virtual/environment
source bin/activate
`

After that, you will be in a clean Python environment.  `pip install bcml` might 'just work' at this point.

To re-use the environment in the future, just cd to the path, and `source bin/activate`
I have my bcml setup with a .desktop file pointing to a shell script to alias python3 to version 3.7, then source the bin/activate, then launch bcml.

**Comment by NiceneNerd** [comment]
I'm going to link this answer in #176 and close this issue, since it's really a duplicate.
