### ISSUE TITLE
Can't run new BCML version

### ISSUE THREAD

**Issue by Makonede** [NiceneNerd/BCML#200]
When attempting to launch BCML, I get the following error:
```py
Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python38\lib\runpy.py". line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python38\lib\site-packages\bcml\__main__.py", line 14, in <module>
    import webviewb as webview
  File "C:\Users\[redacted]\AppData\Roaming\Python\Python38\site-packages\webviewb\__init__.py", line 21, in <module>
    from webviewb.event import Event
ModuleNotFoundError: No module named 'webviewb.event'
```

**Comment by NiceneNerd** [comment]
This probably means there was an installation error.

**Comment by Makonede** [comment]
When installing [this weird thing](https://stackoverflow.com/questions/56973015/pip-how-to-remove-incorrectly-installed-package-with-a-leading-dash-pkgname) happened. I removed `~cml/`, `~cml-3.6.1.dist-info/`, and `~ebviewb/` from `site-packages/`, but kept them in a separate folder just in case. Looking at `~ebviewb/` I can tell that it has some of the files that `site-packages/webviewb/` doesn't, including `event.py`. Why could this be, and how could I fix it?
