### ISSUE TITLE
Issue With Installing syaz0

### ISSUE THREAD

**Issue by GenericGaming** [NiceneNerd/BCML#201]
I've been trying to install bcml for the past half-hour and keep getting stuck at this error:

"ERROR: Command errored out with exit status 1:
     command: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\whitt\\AppData\\Local\\Temp\\pip-install-wowl071t\\syaz0_1cc549bddb3548b491cc3617dd124648\\setup.py'"'"'; __file__='"'"'C:\\Users\\whitt\\AppData\\Local\\Temp\\pip-install-wowl071t\\syaz0_1cc549bddb3548b491cc3617dd124648\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\whitt\AppData\Local\Temp\pip-record-p0s8yknl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\syaz0'
         cwd: C:\Users\whitt\AppData\Local\Temp\pip-install-wowl071t\syaz0_1cc549bddb3548b491cc3617dd124648\
    Complete output (49 lines):
    C:\Python310\lib\site-packages\setuptools\dist.py:484: UserWarning: Normalizing 'v1.0.1' to '1.0.1'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\whitt\AppData\Local\Temp\pip-install-wowl071t\syaz0_1cc549bddb3548b491cc3617dd124648\setup.py", line 25, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "C:\Python310\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Python310\lib\subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Python310\lib\subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\whitt\AppData\Local\Temp\pip-install-wowl071t\syaz0_1cc549bddb3548b491cc3617dd124648\setup.py", line 72, in <module>
        setuptools.setup(
      File "C:\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python310\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python310\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Python310\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python310\lib\distutils\command\install.py", line 568, in run
        self.run_command('build')
      File "C:\Python310\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python310\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Python310\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Python310\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python310\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\whitt\AppData\Local\Temp\pip-install-wowl071t\syaz0_1cc549bddb3548b491cc3617dd124648\setup.py", line 27, in run
        raise RuntimeError("CMake must be installed to build the following extensions: " +
    RuntimeError: CMake must be installed to build the following extensions: syaz0
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\whitt\\AppData\\Local\\Temp\\pip-install-wowl071t\\syaz0_1cc549bddb3548b491cc3617dd124648\\setup.py'"'"'; __file__='"'"'C:\\Users\\whitt\\AppData\\Local\\Temp\\pip-install-wowl071t\\syaz0_1cc549bddb3548b491cc3617dd124648\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\whitt\AppData\Local\Temp\pip-record-p0s8yknl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\syaz0' Check the logs for full command output."
I am very confused as I am very bad at coding.

**Comment by NiceneNerd** [comment]
The problem is your Python version. Per the readme, Python 3.9+ is not supported on Windows.
