### ISSUE TITLE
"Is for Switch, not Switch"

### ISSUE THREAD

**Issue by XenonZe** [NiceneNerd/BCML#204]
Trying to install [this](https://gamebanana.com/mods/49137) . At a loss for what is going on. I'm using switch mode, and my game mode  and files are for and from Switch. Many random mods are throwing this. Are they not compatible with other active mods, are they not compatible with dlc? Any help is appreciated. 

Here's the log

Traceback (most recent call last):
  File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 396, in install_mod
    raise ValueError(
ValueError: "Ultimate Fierce Deity Sword" is for Switch, not  Switch.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 316, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 367, in install_mod
    mods = [
  File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 368, in <listcomp>
    install.install_mod(
  File "c:\users\x\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 426, in install_mod
    raise util.InstallError(err, name) from err
bcml.util.InstallError: An error occured when installing Ultimate Fierce Deity Sword. "Ultimate Fierce Deity Sword" is for Switch, not  Switch.'
Your mod is being removed, and no changes have been made.

I'm launching bcml as I know how, as I suck at python and this was the only method that got it to work

**Comment by NiceneNerd** [comment]
That mod was made with a very old BCML beta and needs to be updated to work

**Comment by XenonZe** [comment]
Oh. What makes it not work? Is it possible to downgrade BCML?

**Comment by NiceneNerd** [comment]
Downgrading BCML is never under any circumstances advised or supported, though it's definitely possible.
