### ISSUE TITLE
Error when switching profile

### ISSUE THREAD

**Issue by OsoaGH** [NiceneNerd/BCML#205]
```
Traceback (most recent call last):
  File "c:\users\tomt0\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 316, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\tomt0\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 332, in set_profile
    rmtree(mod_dir)
  File "c:\users\tomt0\appdata\local\programs\python\python38\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\tomt0\appdata\local\programs\python\python38\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\tomt0\appdata\local\programs\python\python38\lib\shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\tomt0\\AppData\\Local\\bcml\\mods'
```
If I load the profile again, it works

**Comment by jacobjmarks** [comment]
I've also encountered this issue. I have identified the cause and am investigating a fix.
