### ISSUE TITLE
I think I just need help

### ISSUE THREAD

**Issue by Grimmson-Project** [NiceneNerd/BCML#224]
Traceback (most recent call last):
  File "C:\Users\Jack Tuffnail\AppData\Local\Programs\Python\Python37\lib\site-packages\bcml\install.py", line 718, in enable_bcml_gfx
    gpack = settings.getElementsByTagName("GraphicPack")[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jack Tuffnail\AppData\Local\Programs\Python\Python37\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\Jack Tuffnail\AppData\Local\Programs\Python\Python37\lib\site-packages\bcml\install.py", line 317, in do_and_refresh
    refresh_master_export()
  File "C:\Users\Jack Tuffnail\AppData\Local\Programs\Python\Python37\lib\site-packages\bcml\install.py", line 326, in refresh_master_export
    enable_bcml_gfx()
  File "C:\Users\Jack Tuffnail\AppData\Local\Programs\Python\Python37\lib\site-packages\bcml\install.py", line 721, in enable_bcml_gfx
    settings.appendChild(gpack)
  File "C:\Users\Jack Tuffnail\AppData\Local\Programs\Python\Python37\lib\xml\dom\minidom.py", line 1599, in appendChild
    "two document elements disallowed")
xml.dom.HierarchyRequestErr: two document elements disallowed

how do I fix this?

**Comment by GingerAvalanche** [comment]
Looks like your Cemu settings.xml file is corrupted. It's plain text, so you can try to edit it to remove the extra `<document>` element, or you can just delete it and redo your settings the next time you open Cemu.

**Comment by NiceneNerd** [comment]
Sounds like it might be a really old Cemu version
