### ISSUE TITLE
What did I do?

### ISSUE THREAD

**Issue by Johtoboy** [NiceneNerd/BCML#233]
Traceback (most recent call last):
  File "e:\python\lib\site-packages\bcml\util.py", line 606, in get_settings
    settings.update(json.loads(settings_path.read_text()))
  File "e:\python\lib\json__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "e:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "e:\python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 9 column 20 (char 444)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\python\lib\site-packages\bcml_api.py", line 232, in get_mods
    mods = [mod.to_json() for mod in util.get_installed_mods(params["disabled"])]
  File "e:\python\lib\site-packages\bcml\util.py", line 1182, in get_installed_mods
    for info in get_modpack_dir().glob("*/info.json")
  File "e:\python\lib\site-packages\bcml\util.py", line 817, in get_modpack_dir
    return get_storage_dir() / ("mods" if get_settings("wiiu") else "mods_nx")
  File "e:\python\lib\site-packages\bcml\util.py", line 534, in get_storage_dir
    folder = get_settings("store_dir")
  File "e:\python\lib\site-packages\bcml\util.py", line 623, in get_settings
    raise RuntimeError("BCML could not load its settings file") from err
RuntimeError: BCML could not load its settings file

I can't use bcml in any form. I have tried to fix this for some time, but haven't had any luck.

**Comment by NiceneNerd** [comment]
Delete BCML's settings file, then open BCML again and rerun the setup wizard.
