### ISSUE TITLE
"Error merging mods: Copy is out of bounds. Note that this could leave your game in an unplayable state"

### ISSUE THREAD

**Issue by MapAnon** [NiceneNerd/BCML#259]
Doing ANYTHING that involves having to remerge mods brings this message up, telling me it didn't merge correctly. I have all the prereq's installed and freshly installed it, but nothing will get rid of that message.

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\users\USER\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\USER\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\pack.py", line 59, in merge_sarcs
    ) or util.is_file_modded(canon, file_data, count_new=True):
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 974, in is_file_modded
    contents = decompress(contents)
ValueError: Copy is out of bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 653, in refresh_merges
    merger.perform_merge()
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 462, in timed_function
    res = func(*args, **kwargs)
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\pack.py", line 204, in perform_merge
    results = pool.starmap(merge_sarcs, sarcs.items())
  File "c:\users\USER\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "c:\users\USER\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
ValueError: Copy is out of bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 316, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\USER\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 558, in remerge
    raise Exception(
Exception: There was an error merging your mods. Copy is out of bounds
Note that this could leave your game in an unplayable state.

```

**Comment by GingerAvalanche** [comment]
Technical explanation: You have a mod that contains a file that tries to point to data with a pointer that isn't representable by the data type.

English explanation: One of your mods is broken.

I'd assume it's one that's already installed. You could clear your BCMLData folder (which you set in the settings) to uninstall all mods and install them again.

**Comment by MapAnon** [comment]
Odd, [PS4 UI Complete](https://gamebanana.com/mods/33530) doesn't show any comments under it's page that has trouble trying to install the BNP version with this specific problem, but I always do without fail. I even tried the 'Upgrade BNP' option and it gave me the same result.
This also happens with other mods I had no trouble installing before, but now do.
