### ISSUE TITLE
don't know where I goofed up

### ISSUE THREAD

**Issue by baulba** [NiceneNerd/BCML#289]
I've never done anything like this just so you know. im getting this" 'nonetype' object has no attribute 'data' "                error details                                                                                  " Traceback (most recent call last):
  File "c:\users\...\desktop\pypy\lib\site-packages\bcml\_api.py", line 392, in install_mod
    install.refresh_merges()
  File "c:\users\...\desktop\pypy\lib\site-packages\bcml\install.py", line 661, in refresh_merges
    merger.perform_merge()
  File "c:\users\...\desktop\pypy\lib\site-packages\bcml\util.py", line 463, in timed_function
    res = func(*args, **kwargs)
  File "c:\users\dj\desktop\pypy\lib\site-packages\bcml\mergers\data.py", line 242, in perform_merge
    gamedata = consolidate_gamedata(get_stock_gamedata())
  File "c:\users\dj\desktop\pypy\lib\site-packages\bcml\mergers\data.py", line 25, in get_stock_gamedata
    return oead.Sarc(util.decompress(bootup.get_file("GameData/gamedata.ssarc").data))
AttributeError: 'NoneType' object has no attribute 'data' "                                                    
any help would be greatly appreciated

**Comment by NiceneNerd** [comment]
Most likely a problem with your game dump settings

**Comment by NiceneNerd** [comment]
There is no ini. Post your game folder settings.

**Comment by baulba** [comment]
> 

uh what file am i looking for?

**Comment by ArchLeaders** [comment]
Just a screenshot of your settings page. Or preferably the settings file (`%localappdata%\bcml\settings.json`)
