### ISSUE TITLE
White screen on Manjaro 21.2.5

### ISSUE THREAD

**Issue by KenMizz** [NiceneNerd/BCML#299]
I'm using the pipx method, and it's installed on Python 3.8.13. The AUR package error while compling python-oead

I have injected libraries like qtpy and cefpython3

Logs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ken/.local/pipx/venvs/bcml/lib/python3.8/site-packages/bcml/_server.py", line 17, in start_server
    httpd.serve_forever()
  File "/usr/lib/python3.8/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```
![image](https://user-images.githubusercontent.com/16635884/162524945-e55ba3a6-8062-4fda-b47a-4f4360d97a05.png)

**Comment by KenMizz** [comment]
fixed by inject pygobject, looks like qtpy won't work
