### ISSUE TITLE
Where I goof?

### ISSUE THREAD

**Issue by Bored-House** [NiceneNerd/BCML#301]
ERROR: Exception:
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\python39\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\python39\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\python39\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "c:\python39\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "c:\python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "c:\python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\python39\lib\ssl.py", line 1099, in read

**Comment by NiceneNerd** [comment]
What even is this and why are you using an explicitly unsupported Python version?
