### ISSUE TITLE
I tried to create a custom switch text mod but on build, I have this error

### ISSUE THREAD

**Issue by Sleora** [NiceneNerd/BCML#303]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\texts.py", line 193, in diff_msyt
    contents = json.loads(text)
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\texts.py", line 335, in log_diff
    diff_material = self.generate_diff(mod_dir, diff_material)
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\texts.py", line 323, in generate_diff
    language_diffs[language] = diff_language(
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\texts.py", line 241, in diff_language
    results = this_pool.map(
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 640, in create_bnp
    dev.create_bnp_mod(
  File "c:\users\aroel\appdata\local\programs\python\python38\lib\site-packages\bcml\dev.py", line 418, in create_bnp_mod
    raise Exception(
Exception: There was an error generating change logs for your mod. Expecting value: line 1 column 1 (char 0)

```

**Comment by NiceneNerd** [comment]
What tool did you use to make the text mod, and what did you change?

**Comment by Sleora** [comment]
I used Visual Studio 2019 to edit the already existing texts to change dialogues. I didn't added or removed anything.
