### ISSUE TITLE
BCML throws an exception when trying to build/re-merge using a 32-core/64 thread CPU

### ISSUE THREAD

**Issue by duerra** [NiceneNerd/BCML#314]
See below for the stack trace.  The execution does not successfully complete a mod build.

```
> bcml-debug
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:59977/devtools/browser/0be2145d-bd5a-4136-817b-42af4fb3bb2f
CEF window with uid master does not exist
CEF window with uid master does not exist
Exception in thread Thread-15:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python38\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\python38\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
[0427/072630.943:ERROR:request_handler.cpp(109)] [Browser process] OnRenderProcessTerminated()
```

**Comment by GingerAvalanche** [comment]
Is this still a problem? The core of this issue is that the `multiprocessing` package does (or didn't) support 64 threads, and this may have changed in the past 2.5 months.

If it hasn't, I've found a way to force it to use fewer threads. Please let us know, because we don't have 64-thread CPUs and can't test.

**Comment by NiceneNerd** [comment]
I keep forgetting, it's actually pretty easy to change the call to limit the process count. I'll look at that today.
