### ISSUE TITLE
New error after updating BCML

### ISSUE THREAD

**Issue by TheMythicGamer** [NiceneNerd/BCML#318]
`Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 550, in remerge
    install.refresh_merges()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 661, in refresh_merges
    merger.perform_merge()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 462, in timed_function
    res = func(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\quests.py", line 167, in perform_merge
    add.pop("prev_quest", None)
AttributeError: 'oead.byml.Hash' object has no attribute 'pop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 324, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 558, in remerge
    raise Exception(
Exception: There was an error merging your mods. 'oead.byml.Hash' object has no attribute 'pop'
Note that this could leave your game in an unplayable state.
`

**Comment by GingerAvalanche** [comment]
Only reopening so that it still exists until the new PR is pulled
