### ISSUE TITLE
error after update bcml :

### ISSUE THREAD

**Issue by FUREURe** [NiceneNerd/BCML#320]
[2022-05-03 22:37:21] Traceback (most recent call last):
  File "c:\users\name\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\name\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\AppData\Local\Programs\Python\Python38\Scripts\bcml.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\name\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 144, in main
    api.window.events.closing += stop_it
AttributeError: 'Window' object has no attribute 'events'

**Comment by NiceneNerd** [comment]
Upgrade pywebview: `pip install -U pywebview`

**Comment by FUREURe** [comment]
already done and not work

**Comment by FUREURe** [comment]
PS C:\Windows\system32> pip install pywebview
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Collecting pywebview
  Using cached pywebview-3.6.3-py3-none-any.whl (351 kB)
Collecting pythonnet
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: proxy-tools in c:\python310\lib\site-packages (from pywebview) (0.1.0)
Requirement already satisfied: pycparser in c:\python310\lib\site-packages (from pythonnet->pywebview) (2.21)
Using legacy 'setup.py install' for pythonnet, since package 'wheel' is not installed.
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Installing collected packages: pythonnet, pywebview
  Running setup.py install for pythonnet ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pythonnet did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: option --single-version-externally-managed not recognized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pythonnet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)

**Comment by NiceneNerd** [comment]
Don't use Python 3.10

**Comment by FUREURe** [comment]
I was going to say that I found the solution: by installing another version of python I unfortunately changed the path. so after each installation of python recheck the path

**Comment by GingerAvalanche** [comment]
Sorry about that, got confused and thought this error was the same as 318. Should be all good now. (Logs still tie this issue to 321, but I guess that just means we'll forever have evidence of my shame)
