### ISSUE TITLE
Failed when installing mod in a Chinese system environment

### ISSUE THREAD

**Issue by xitieshiz2** [NiceneNerd/BCML#328]
Full error detail:
````
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\bcml\install.py", line 325, in do_and_refresh
    refresh_master_export()
  File "c:\program files\python38\lib\site-packages\bcml\install.py", line 334, in refresh_master_export
    enable_bcml_gfx()
  File "c:\program files\python38\lib\site-packages\bcml\install.py", line 724, in enable_bcml_gfx
    settings = util.parse_cemu_settings()
  File "c:\program files\python38\lib\site-packages\bcml\util.py", line 657, in parse_cemu_settings
    for line in setfile:
  File "c:\program files\python38\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 4737: invalid start byte

````
System: Windows 11 22000.652
System language: Simplified Chinese (PRC)
This happens with every mod, possible solution: add a button to switch the 'encoding' between 'utf-8' and 'gbk' when reading files.

**Comment by GingerAvalanche** [comment]
Can you upload your cemu `settings.xml` here? Need to make sure that the assumptions bcml makes about the layout will actually work with `gpk` encoding.
