### ISSUE TITLE
Copy is out of bounds

### ISSUE THREAD

**Issue by rico-387** [NiceneNerd/BCML#331]
When I try and do literally anything with BCML (install mod, remerge, export) I get this error: 

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 121, in worker
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 47, in starmapstar
  File "C:\bcml\Python\lib\site-packages\bcml\mergers\pack.py", line 59, in merge_sarcs
    ) or util.is_file_modded(canon, file_data, count_new=True):
  File "C:\bcml\Python\lib\site-packages\bcml\util.py", line 981, in is_file_modded
    contents = decompress(contents)
ValueError: Copy is out of bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\bcml\Python\lib\site-packages\bcml\install.py", line 661, in refresh_merges
    merger.perform_merge()
  File "C:\bcml\Python\lib\site-packages\bcml\util.py", line 462, in timed_function
    res = func(*args, **kwargs)
  File "C:\bcml\Python\lib\site-packages\bcml\mergers\pack.py", line 204, in perform_merge
    results = pool.starmap(merge_sarcs, sarcs.items())
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 276, in starmap
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 657, in get
ValueError: Copy is out of bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bcml\Python\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "C:\bcml\Python\lib\site-packages\bcml\install.py", line 324, in do_and_refresh
    res = func(*args, **kwargs)
  File "C:\bcml\Python\lib\site-packages\bcml\_api.py", line 559, in remerge
    f"There was an error merging your mods. {str(err)}\n"
Exception: There was an error merging your mods. Copy is out of bounds
Note that this could leave your game in an unplayable state.

**Comment by rico-387** [comment]
I'm in switch mode and I'm trying to export mods to switch, this happened when I tried to install Second Wind and when I tried to install the Linkle mod separately.

**Comment by GingerAvalanche** [comment]
`Copy is out of bounds` is an old yaz0 error involving files that were compressed incorrectly. It pops up every once in a while, but as far as I know, nobody knows how, exactly, their compression is wrong, so nobody can make a very permanent fix.

Find your bcml installation with the console command `pip show bcml`, then go to the folder listed as the install folder. It'll be called `bcml`. Inside that folder, open `util.py` with a text editor.

Change line 982 so that it says `        except ValueError as err:` (basically, just change `RuntimeError` to say `ValueError` instead)

Close and reopen bcml and try to install either/both of those mods again. The error should now say what file caused it.

**Comment by rico-387** [comment]
I tried to remerge Second Wind, I got this error: 

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\bcml\Python\lib\site-packages\bcml\util.py", line 981, in is_file_modded
    contents = decompress(contents)
ValueError: Copy is out of bounds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 121, in worker
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 47, in starmapstar
  File "C:\bcml\Python\lib\site-packages\bcml\mergers\pack.py", line 59, in merge_sarcs
    ) or util.is_file_modded(canon, file_data, count_new=True):
  File "C:\bcml\Python\lib\site-packages\bcml\util.py", line 983, in is_file_modded
    raise ValueError(f"Invalid yaz0 file {name}") from err
ValueError: Invalid yaz0 file Model/Terrain.Tex.bfres
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\bcml\Python\lib\site-packages\bcml\install.py", line 661, in refresh_merges
    merger.perform_merge()
  File "C:\bcml\Python\lib\site-packages\bcml\util.py", line 462, in timed_function
    res = func(*args, **kwargs)
  File "C:\bcml\Python\lib\site-packages\bcml\mergers\pack.py", line 204, in perform_merge
    results = pool.starmap(merge_sarcs, sarcs.items())
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 276, in starmap
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 657, in get
ValueError: Invalid yaz0 file Model/Terrain.Tex.bfres

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bcml\Python\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "C:\bcml\Python\lib\site-packages\bcml\install.py", line 324, in do_and_refresh
    res = func(*args, **kwargs)
  File "C:\bcml\Python\lib\site-packages\bcml\_api.py", line 559, in remerge
    f"There was an error merging your mods. {str(err)}\n"
Exception: There was an error merging your mods. Invalid yaz0 file Model/Terrain.Tex.bfres
Note that this could leave your game in an unplayable state.

**Comment by rico-387** [comment]
Wait, I may have found the issue - My base directory is the old version, give me an hour to redump the updated version.

**Comment by rico-387** [comment]
Do I need to revert util.py line 982 back to runtimeError?

**Comment by GingerAvalanche** [comment]
No. It being RuntimeError was a bug anyway. It was supposed to turn the useless error message into something useful, but it didn't because until you changed it to ValueError, it was looking for the wrong error.

**Comment by rico-387** [comment]
I dumped the wrong game version. I hope this helps someone who makes the same stupid mistake that I did, my pride has not taken this well lol
