### ISSUE TITLE
Issue adding mod- seems to be a problem with Merger

### ISSUE THREAD

**Issue by arrodriguez92** [NiceneNerd/BCML#348]
I am using BCML 3.9.5 in CEMU/WiiU mode with Python 3.9.13.
while i am trying to install/add Zelda ballad zip gives me this error. other zips like the zelda ballad shield fix and bmp works just fine 
```
Traceback (most recent call last):
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\install.py", line 368, in install_mod
    generate_logs(tmp_dir=tmp_dir, options=options, pool=this_pool)
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\install.py", line 246, in generate_logs
    merger.log_diff(tmp_dir, modded_files)
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\mergers\texts.py", line 123, in log_diff
    diff_material = self.generate_diff(mod_dir, diff_material)
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\mergers\texts.py", line 111, in generate_diff
    language_diffs[language] = rsext.mergers.texts.diff_language(
Exception: Error handling MSBT file: Could not parse EventFlowMsg/CarryingBlueFireEXMini.msbt.bak: io error: failed to fill whole buffer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\install.py", line 265, in do_and_refresh
    res = func(*args, **kwargs)
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\_api.py", line 380, in install_mod
    mods = [
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\_api.py", line 381, in <listcomp>
    install.install_mod(
  File "C:\Users\arrod\AppData\Roaming\Python\Python39\site-packages\bcml\install.py", line 376, in install_mod
    raise util.InstallError(err, name) from err
bcml.util.InstallError: An error occured when installing Zelda's Ballad - Link Animations. Error handling MSBT file: Could not parse EventFlowMsg/CarryingBlueFireEXMini.msbt.bak: io error: failed to fill whole buffer
Your mod is being removed, and no changes have been made.
```

running bcml-debug gives this before listing my installed mods again

```
Opening mod...
Looks like an older mod, let's upgrade it...
Converting meta file...
Identified mod: Zelda's Ballad - Link Animations
VERBOSE{
  "disable": [],
  "options": {}
}
Scanning for modified files...
Finding modified files...
Found 1048 modified files...
Found 224 modified files in SARCs...
VERBOSEMerger packs, #1 of 18
Finding modified SARCs...
VERBOSEMerger aamp, #2 of 18
Detecting general changes to AAMP files...
VERBOSEMerger drops, #3 of 18
VERBOSEMerger shop, #4 of 18
Detecting changes to shop files...
VERBOSEMerger aslist, #5 of 18
Detecting general changes to AS lists...
VERBOSEMerger texts, #6 of 18
Checking for modified languages...
VERBOSELanguages: USen,EUen
VERBOSELanguage map:
VERBOSE{
  "USen": "USen"
}
```

**Comment by NiceneNerd** [comment]
It's a problem with the mod including junk files inside its message pack. Previous BCML versions ignored anything that wasn't an MSBT file in a message pack, but now it just iterates the files and expects them all to be valid (since there never *should* be anything else in a public mod release).

If you replace `Pack/Bootup_USen.pack` in the Zelda's Ballad RAR with this version it should work
[Bootup_USen.pack.zip](https://github.com/NiceneNerd/BCML/files/8847934/Bootup_USen.pack.zip)

**Comment by Torphedo** [comment]
Shouldn't it go back to ignoring files without an MSBT extension? Might be *slightly* slower but imo is worth it for ease of use

**Comment by arrodriguez92** [comment]
> It's a problem with the mod including junk files inside its message pack. Previous BCML versions ignored anything that wasn't an MSBT file in a message pack, but now it just iterates the files and expects them all to be valid (since there never _should_ be anything else in a public mod release).
> 
> If you replace `content/Pack/Bootup_USen.pack` in the Zelda's Ballad RAR with this version it should work [Bootup_USen.pack.zip](https://github.com/NiceneNerd/BCML/files/8847934/Bootup_USen.pack.zip)

can confirm. just replacing that file and repacking the rar fixed the issue thanks for the quick reply
