### ISSUE TITLE
Failed to open BCML

### ISSUE THREAD

**Issue by hmohammedtaha** [NiceneNerd/BCML#361]
I tried opening the shortcut as well as from command line but with no success.

Error code generated is : 

[2022-06-18 22:18:57] Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\bcml\__main__.py", line 158, in <module>
    main()
  File "C:\Python38\lib\site-packages\bcml\__main__.py", line 97, in main
    configure_cef(debug)
  File "C:\Python38\lib\site-packages\bcml\__main__.py", line 51, in configure_cef
    cache = util.get_storage_dir() / "cef_cache"
  File "C:\Python38\lib\site-packages\bcml\util.py", line 543, in get_storage_dir
    raise FileNotFoundError("No storage folder available")
FileNotFoundError: No storage folder available

**Comment by GingerAvalanche** [comment]
In your local app data (start menu, search `%LOCALAPPDATA%` and hit enter) go into the bcml folder and delete settings.json. Boot bcml and put all your settings back in.

**Comment by hmohammedtaha** [comment]
Thanks, it worked
