### ISSUE TITLE
Getting an error when installing BCML using pip 

### ISSUE THREAD

**Issue by Sunshine-Leona** [NiceneNerd/BCML#371]
Hello, 

I get the following error when I try to install BCML. Please note that I have downloaded latest x64 Visual C++.  I would appreciate any feedback. Thank you.
![image](https://user-images.githubusercontent.com/35029399/175975958-fd808b1b-4fd0-4e84-bb0e-5622329ae856.png)

Error:

Microsoft Windows [Version 10.0.22000.739]
(c) Microsoft Corporation. All rights reserved.

C:\Users\toofi>pip install bcml
Defaulting to user installation because normal site-packages is not writeable
Collecting bcml
  Using cached bcml-3.9.12-cp39-none-win_amd64.whl (19.0 MB)
Collecting aamp~=1.4.1
  Using cached aamp-1.4.1-py3-none-any.whl (337 kB)
Collecting numpy==1.19.2
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [200 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\bit_generator.pyx
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Processing numpy/random\_pcg64.pyx
      Processing numpy/random\_philox.pyx
      Processing numpy/random\_sfc64.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      C:\Users\toofi\AppData\Local\Temp\pip-install-5vvwi37w\numpy_3b65d0b1c0ed4be2b94a8936838c4953\numpy\distutils\system_info.py:1914: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      blas_info:
        libraries blas not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      C:\Users\toofi\AppData\Local\Temp\pip-install-5vvwi37w\numpy_3b65d0b1c0ed4be2b94a8936838c4953\numpy\distutils\system_info.py:1914: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      blas_src_info:
        NOT AVAILABLE

      C:\Users\toofi\AppData\Local\Temp\pip-install-5vvwi37w\numpy_3b65d0b1c0ed4be2b94a8936838c4953\numpy\distutils\system_info.py:1914: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
        NOT AVAILABLE

      non-existing path in 'numpy\\distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      openblas_lapack_info:
        libraries openblas not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      openblas_clapack_info:
        libraries openblas,lapack not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      flame_info:
        libraries flame not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Program Files\Python39\lib
        libraries tatlas,tatlas not found in C:\Program Files\Python39\lib
        libraries lapack_atlas not found in C:\
        libraries tatlas,tatlas not found in C:\
        libraries lapack_atlas not found in C:\Program Files\Python39\libs
        libraries tatlas,tatlas not found in C:\Program Files\Python39\libs
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
        libraries lapack_atlas not found in C:\Program Files\Python39\lib
        libraries satlas,satlas not found in C:\Program Files\Python39\lib
        libraries lapack_atlas not found in C:\
        libraries satlas,satlas not found in C:\
        libraries lapack_atlas not found in C:\Program Files\Python39\libs
        libraries satlas,satlas not found in C:\Program Files\Python39\libs
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Program Files\Python39\lib
        libraries ptf77blas,ptcblas,atlas not found in C:\Program Files\Python39\lib
        libraries lapack_atlas not found in C:\
        libraries ptf77blas,ptcblas,atlas not found in C:\
        libraries lapack_atlas not found in C:\Program Files\Python39\libs
        libraries ptf77blas,ptcblas,atlas not found in C:\Program Files\Python39\libs
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
        libraries lapack_atlas not found in C:\Program Files\Python39\lib
        libraries f77blas,cblas,atlas not found in C:\Program Files\Python39\lib
        libraries lapack_atlas not found in C:\
        libraries f77blas,cblas,atlas not found in C:\
        libraries lapack_atlas not found in C:\Program Files\Python39\libs
        libraries f77blas,cblas,atlas not found in C:\Program Files\Python39\libs
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
        libraries lapack not found in ['C:\\Program Files\\Python39\\lib', 'C:\\', 'C:\\Program Files\\Python39\\libs']
        NOT AVAILABLE

      C:\Users\toofi\AppData\Local\Temp\pip-install-5vvwi37w\numpy_3b65d0b1c0ed4be2b94a8936838c4953\numpy\distutils\system_info.py:1748: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\toofi\AppData\Local\Temp\pip-install-5vvwi37w\numpy_3b65d0b1c0ed4be2b94a8936838c4953\numpy\distutils\system_info.py:1748: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
        NOT AVAILABLE

      numpy_linalg_lapack_lite:
        FOUND:
          language = c
          define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

      C:\Program Files\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win-amd64-3.9
      creating build\src.win-amd64-3.9\numpy
      creating build\src.win-amd64-3.9\numpy\distutils
      building library "npymath" sources
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Program Files\Python39\python.exe -m pip install --upgrade pip' command.

**Comment by NiceneNerd** [comment]
First try upgrading pip per the last warning. If that doesn't work switch to Python 3.8.

**Comment by ratijas** [comment]
Update: installs fine with latest Python 3.9 branch.

However, does not start. When running `python -m bcml` from a command line, the following error is printed:

```
C:\Users\ratijas\AppData\Local\Programs\Python\Python39\Lib\site-packages> python -m bcml
Traceback (most recent call last):
  File "C:\Users\ratijas\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ratijas\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ratijas\AppData\Local\Programs\Python\Python39\Lib\site-packages\bcml\__main__.py", line 19, in <module>
    from bcml._api import Api
  File "C:\Users\ratijas\AppData\Local\Programs\Python\Python39\Lib\site-packages\bcml\_api.py", line 12, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by NiceneNerd** [comment]
3.9 support on Windows is flaky and experimental. Use the latest version of 3.8 that has an installer.

**Comment by ratijas** [comment]
> 3.9 support on Windows is flaky and experimental. Use the latest version of 3.8 that has an installer.

Note that while being "better than nothing", installing an older version without the latest security fixes is kind of a bad advice, especially for non tech-savvy folks out there

**Comment by NiceneNerd** [comment]
Unfortunately, nothing can be done about that since the Python devs make tons of breaking changes with each new release and some important dependencies take years to get updated
