### ISSUE TITLE
unable to finalize remerge, due to "the file or directory is not a reparse point."

### ISSUE THREAD

**Issue by CatEyedLin** [NiceneNerd/BCML#383]
any attempt to remerge mods, gets the traceback from below.

i have tried reinstalling BCML, changing cemu directory, BCML Data directory, disabling hard links for master mod, and using BCML without a Cemu installation

i've used BCML before without issue, but even trying to reset everything i can think of, still results in the issue

...
    "E:/Emulators\\cemu_1.20.2\\BCML3.0\\data\\mods\\9999_BCML",
    "E:/Emulators\\cemu_1.20.2\\BCML3.0\\data\\mods\\content",
]
Clearing output folder at C:\Users\Lin\Home\cemu_1.25.1\graphicPacks\BreathOfTheWild_BCML
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 4390, kind: Uncategorized, message: "The file or directory is not a reparse point." }', src\manager.rs:125:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-52:
Traceback (most recent call last):
  File "c:\users\lin\appdata\local\programs\python\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\users\lin\appdata\local\programs\python\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\lin\appdata\local\programs\python\python37\lib\site-packages\webview\util.py", line 138, in _call
    result = func(*func_params.values())
  File "c:\users\lin\appdata\local\programs\python\python37\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\lin\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 265, in do_and_refresh
    refresh_master_export()
  File "c:\users\lin\appdata\local\programs\python\python37\lib\site-packages\bcml\util.py", line 463, in timed_function
    res = func(*args, **kwargs)
  File "c:\users\lin\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 274, in refresh_master_export
    link_master_mod()
  File "c:\users\lin\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 745, in link_master_mod
    rsext.manager.link_master_mod(str(output) if output else None)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Os { code: 4390, kind: Uncategorized, message: "The file or directory is not a reparse point." }

**Comment by NiceneNerd** [comment]
First try deleting `C:\Users\Lin\Home\cemu_1.25.1\graphicPacks\BreathOfTheWild_BCML`

**Comment by CatEyedLin** [comment]
oh yup, that worked, i thought i tried that, sorry for that
thank you!
