### ISSUE TITLE
Crash when trying to launch BCML

### ISSUE THREAD

**Issue by chrisheinonen** [NiceneNerd/BCML#387]
Installing on two computers around the house, both with Python 3.9.13 and latest VC++ Build Redistributables, and getting this error on both machines when using bcml-debug:
```
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:55003/devtools/browser/44b18458-69d0-47a3-80e9-2e9c1a8d9c20

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by HGStone** [comment]
Python 3.9 is kinda not working good.. should stick with this one.  https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe
