### ISSUE TITLE
Stock Map File Could Not Be Found. Relics of the Past Installation Error.

### ISSUE THREAD

**Issue by Sunshine-Leona** [NiceneNerd/BCML#389]
Hello,

I get this error when trying to install Relics of the Past using BCML. I'm using the info.json file to install the mod. I had gotten an error related to TitleBG.pack so I copied the file from the mod and pasted it into the BoTW Dump:

![image](https://user-images.githubusercontent.com/35029399/178679044-7f295fac-3b9f-4490-bf2d-35506ceeb0d0.png)

I also tried converting the mod into a BNP but I get the same error (stock map file). Thanks in advance.

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\program files\python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\mergers\mubin.py", line 185, in get_map_diff
    base_map = get_stock_map(map_unit, force_vanilla=stock_map)
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\mergers\mubin.py", line 102, in get_stock_map
    raise FileNotFoundError(
FileNotFoundError: The stock map file A-5_Static.smubin could not be found.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\mergers\mubin.py", line 557, in log_diff
    diff_material = self.generate_diff(mod_dir, diff_material)
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\mergers\mubin.py", line 547, in generate_diff
    return generate_modded_map_log(
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\mergers\mubin.py", line 279, in generate_modded_map_log
    {
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\mergers\mubin.py", line 279, in <dictcomp>
    {
  File "c:\program files\python38\lib\multiprocessing\pool.py", line 868, in next
    raise value
FileNotFoundError: The stock map file A-5_Static.smubin could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\install.py", line 324, in do_and_refresh
    res = func(*args, **kwargs)
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\_api.py", line 380, in install_mod
    mods = [
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\_api.py", line 381, in <listcomp>
    install.install_mod(
  File "C:\Users\toofi\AppData\Roaming\Python\Python38\site-packages\bcml\install.py", line 434, in install_mod
    raise util.InstallError(err, name) from err
bcml.util.InstallError: An error occured when installing Official Final Beta Version 2.9.6b. The stock map file A-5_Static.smubin could not be found.
Your mod is being removed, and no changes have been made.

**Comment by GingerAvalanche** [comment]
Unfortunately, we can't help you diagnose an issue if you've modified your game dump, especially TitleBG.

Since the file mentioned in your error is normally found in your game dump's TitleBG, I would hazard a guess that the TitleBG you replaced in your dump doesn't have that file, but can't verify.

If you still have your original TitleBG backed up, you can put it back in your dump and then share the error you get from that, and we can try and diagnose that error. Since it will be a different error than this one, though, I'm going to close this one.
