### ISSUE TITLE
```IsADirectoryError: [Errno 21] Is a directory: '/'```

### ISSUE THREAD

**Issue by AM7999** [NiceneNerd/BCML#390]
After trying to create a BNP for a mod on Manjaro Linux (with regular Arch repos) i get the error ```"IsADirectoryError: [Errno 21] Is a directory: '/'``` The error log is as follows: 

```Traceback (most recent call last):
  File "/home/_____/.local/lib/python3.8/site-packages/bcml/_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "/home/______/.local/lib/python3.8/site-packages/bcml/_api.py", line 652, in create_bnp
    dev.create_bnp_mod(
  File "/home/______/.local/lib/python3.8/site-packages/bcml/dev.py", line 441, in create_bnp_mod
    output.unlink()
  File "/usr/lib/python3.8/pathlib.py", line 1325, in unlink
    self._accessor.unlink(self)
IsADirectoryError: [Errno 21] Is a directory: '/'```

**Comment by GingerAvalanche** [comment]
It appears that you've not chosen an output for your bnp file, so it's defaulting to your root folder.

**Comment by AM7999** [comment]
Strange... i set the output directory to be my own home folder yet its still trying to output to my root folder (im setting the output using the popup window)
