### ISSUE TITLE
BCML won't launch after install

### ISSUE THREAD

**Issue by Nucl34r-Fr06** [NiceneNerd/BCML#391]
Just tried to install BCML with the latest stuff and after a successful install, it will not launch at all. No errors or anything, just won't ever come up. I've tried uninstalling and reinstalling BCML itself and python to a different directory to no avail. I've also tried launching BCML through cmd and in the python folder. Any help would be greatly appreciated!

**Comment by Nucl34r-Fr06** [comment]
I just tried launching the "bcml-debug.exe" to see what might happen and got this in the window, thought it might be helpful

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

**Comment by GingerAvalanche** [comment]
The renderer (the thing that draws the bcml window on the screen) is trying to get a cache that doesn't exist. The renderer is mostly self-contained, and this isn't something bcml has much control over. There must've been a breaking change with it, recently. I'll look into it.

**Comment by NiceneNerd** [comment]
Are you using Python 3.9? Python 3.9 support is still wonky, and that looks like some of the errors I've seen.

**Comment by Nucl34r-Fr06** [comment]
I was using the most recent python 3.9 release, I'll try to reinstall with 3.8
