### ISSUE TITLE
Oops! Output folder is empty

### ISSUE THREAD

**Issue by exJad** [NiceneNerd/BCML#398]
I installed BCML a week or so ago, and got everything working, merged a few mods and made them work on my nintendo switch. Recently though, my BCML has stopped working. I've tried updating, deleting settings, even uninstalling and reinstalling, but whenever I try to install a bnp or export a mod, I get an error like this:

Oops! Output folder is empty

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\install.py", line 265, in do_and_refresh
    refresh_master_export()
  File "c:\python38\lib\site-packages\bcml\util.py", line 463, in timed_function
    res = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\install.py", line 274, in refresh_master_export
    link_master_mod()
  File "c:\python38\lib\site-packages\bcml\install.py", line 745, in link_master_mod
    rsext.manager.link_master_mod(str(output) if output else None)
RuntimeError: Output folder is empty

**Comment by GingerAvalanche** [comment]
Try updating to 3.9.21 and seeing if that fixes it?

**Comment by boyooo** [comment]
getting this same issue
