### ISSUE TITLE
BCML wants to access temp folders that don't exist

### ISSUE THREAD

**Issue by jekkkk** [NiceneNerd/BCML#399]
Traceback (most recent call last):
  File "c:\users\*****\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\*****\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 630, in export
    install.export(output)
  File "c:\users\*****\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 816, in export
    raise RuntimeError(
RuntimeError: There was an error exporting your mod(s). 
WARNING: The system cannot find the path specified.
C:\Users\*****\AppData\Local\Temp\tmpali88437\

**Comment by jekkkk** [comment]
Also if I make a file with that name it just asks for another one when trying to export as a zip.

**Comment by GingerAvalanche** [comment]
The temp folders exist, because bcml creates them. They then don't exist, because bcml deletes them when you export. Don't use the export button, it's broken, as this issue illustrates.

Go to BCML's settings, set an export directory, check the disable hard links button, and then your files will be where you want them when you install/remerge.
