### ISSUE TITLE
Oops！could not parse control sequences Casued by:0 could not parse control sequence 2 1:could not parse control sub type 18 2:could not read string bytes 3:failed to fill whole buffer

### ISSUE THREAD

**Issue by zoustGIHUB** [NiceneNerd/BCML#408]
Please how can I solve the problem, when I want to install the latest version of the second wild, the following problem always occurs (I tried cemu two versions (1.26.2 and 1.27.1) and three Python versions)
![图片](https://user-images.githubusercontent.com/32449101/182008426-3755eed2-d307-4706-9b2d-920f0b4b3696.png)
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\bcml\install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\_api.py", line 404, in install_mod
    install.refresh_merges()
  File "c:\python38\lib\site-packages\bcml\install.py", line 602, in refresh_merges
    merger.perform_merge()
  File "c:\python38\lib\site-packages\bcml\util.py", line 463, in timed_function
    res = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\mergers\texts.py", line 217, in perform_merge
    rsext.mergers.texts.merge_language(
RuntimeError: could not parse control sequences

Caused by:
    0: could not parse control sequence 2
    1: could not parse control subtype 18
    2: could not read string bytes
    3: failed to fill whole buffer

**Comment by NiceneNerd** [comment]
Seems like perhaps the newest SW build might have some kind of corrupt text file? That's all I can think of

**Comment by zoustGIHUB** [comment]
Thanks for the explanation
