### ISSUE TITLE
cant export mods. please help me

### ISSUE THREAD

**Issue by S1ayerXYZ** [NiceneNerd/BCML#414]
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\_api.py", line 630, in export
    install.export(output)
  File "c:\python38\lib\site-packages\bcml\install.py", line 819, in export
    raise RuntimeError(
RuntimeError: There was an error exporting your mod(s). 
WARNING: The system cannot find the path specified.
C:\Users\pikac\AppData\Local\Temp\tmpwhcvof_z\

**Comment by NiceneNerd** [comment]
Did you try the setting to disable hard links?

**Comment by EeyoreDude** [comment]
Same issue on versions 3.9.18 and after. Python version 3.8.8.
I'm using switch mode.

The disable hard links setting is greyed out:
![image](https://user-images.githubusercontent.com/35280511/187335371-4ba2d468-e383-4c5e-bd9a-91913598830b.png)

The video I was following used version 3.8.0 so I tried reverting a few versions to see if that would fix it.
The most recent version where I didn't get the error was 3.9.17

**Comment by NiceneNerd** [comment]
The issue with the hard links option being greyed out was fixed relatively recently, I recommend using the latest or at least 3.9.24.

**Comment by Luiaves** [comment]
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 630, in export
    install.export(output)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 819, in export
    raise RuntimeError(
RuntimeError: There was an error exporting your mod(s). 
WARNING: The system cannot find the path specified.
C:\Users\User\AppData\Local\Temp\tmp8pody7q2\

**Comment by Luiaves** [comment]
i disabled links but its still giving me this error, do i have to restart bcml?
