### ISSUE TITLE
unable to start BCML

### ISSUE THREAD

**Issue by tatsumasagc** [NiceneNerd/BCML#417]
i am running Windows 11 build 22000.856
Python 3.9.13

when I install bcml via `pip install bcml` and when I install/build from the source I cannot get bcml to start

- when I run `bcml` in cmd or ps it appears to do nothing - 
- when I run `python -m bcml` it displays the following error
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

- when I go to my python scripts folder and run bcml.exe, it appears to do nothing, but bcml.exe shows up on the task manager for a few seconds before closing again.

**Comment by tatsumasagc** [comment]
Nevermind, it was a Python 3.9 issue, I uninstalled 3.9 and reinstalled 3.8 and tried again and it worked fine
