### ISSUE TITLE
Game dump error?

### ISSUE THREAD

**Issue by 7MRZ** [NiceneNerd/BCML#428]
Hey idk if this is a problem with BCML loading in a mod or my BOTW downloads. I downloaded the BOTW Randomizer by waikuteru, installed the rules txt, and keep getting this error:

FileNotFoundError: File Actor\Pack\TitleBG.pack\Actor\Pack\GameROMPlayer.sbactorpack was not found in game dump.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 121, in worker
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 47, in starmapstar
  File "C:\Users\r\pkgs\bcml\mergers\drop.py", line 124, in merge_drop_file
    util.inject_files_into_actor(actor_name, {file.split("//")[-1]: pio.to_binary()})
  File "C:\Users\r\pkgs\bcml\util.py", line 993, in inject_files_into_actor
    actor_path = get_game_file(f"Actor/Pack/{actor}.sbactorpack")
  File "C:\Users\r\pkgs\bcml\util.py", line 822, in get_game_file
    raise FileNotFoundError(f"File {str(path)} was not found in game dump.")
FileNotFoundError: File Actor\Pack\TitleBG.pack\Actor\Pack\GameROMPlayer.sbactorpack was not found in game dump.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\r\pkgs\bcml\install.py", line 595, in refresh_merges
    merger.perform_merge()
  File "C:\Users\r\pkgs\bcml\util.py", line 447, in timed_function
    res = func(*args, **kwargs)
  File "C:\Users\r\pkgs\bcml\mergers\drop.py", line 191, in perform_merge
    pool.starmap(merge_drop_file, diffs.items())
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 276, in starmap
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 657, in get
FileNotFoundError: File Actor\Pack\TitleBG.pack\Actor\Pack\GameROMPlayer.sbactorpack was not found in game dump.

So... game error, BCML error, or Cemu/botw error? Any fixes?

**Comment by NiceneNerd** [comment]
Probably your settings. What are they?

**Comment by 7MRZ** [comment]
Sorry what do you mean by settings?

**Comment by NiceneNerd** [comment]
Your BCML settings

**Comment by ArchLeaders** [comment]
> Sorry what do you mean by settings? Edit: Where can I find these settings? Idk them

They're in `%LOCALAPPDATA%\bcml\` (`settings.json`)

**Comment by 7MRZ** [comment]
Hey so I uninstalled everything including BCML and Python, reinstalled it, and installed the Randomizer Mod via the One Click One Install feature, even that didin’t work, but if you spam it a couple of times it finally registers. I think it was due to my Python version being a bit wack. It’s fixed now

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
