### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by TheBaconGod** [NiceneNerd/BCML#443]
I have been trying for over an hour to get bcml to launch to no avail. when I run the command to launch it my computer process it but nothing opens but the debug file will open. I have tried running it as an administrator and everything else I could find that could possibly be wrong with no results.

**Comment by ArchLeaders** [comment]
What does `python -m bcml` print?

**Comment by TheBaconGod** [comment]
it prints this
[pywebview] Using WinForms / CEF
[1102/082306.683:INFO:cefpython_app.cpp(199)] [Browser process] OnBeforeChildProcessLaunch() command line: "C:\Python\Python39\lib\site-packages\cefpython3\subprocess.exe" --type=gpu-process --no-sandbox --locales-dir-path="C:\Python\Python39\lib\site-packages\cefpython3\locales" --log-file="C:\Users\Andrew\debug.log" --log-severity=info --resources-dir-path="C:\Python\Python39\lib\site-packages\cefpython3" --lang=en-US --enable-media-stream /prefetch:2

[1102/082306.685:INFO:cef_log.cpp(8)] [Browser process] Switch already set, ignoring: enable-media-stream

[1102/082306.685:INFO:cefpython_app.cpp(199)] [Browser process] OnBeforeChildProcessLaunch() command line: "C:\Python\Python39\lib\site-packages\cefpython3\subprocess.exe" --type=gpu-process --no-sandbox --locales-dir-path="C:\Python\Python39\lib\site-packages\cefpython3\locales" --log-file="C:\Users\Andrew\debug.log" --log-severity=info --resources-dir-path="C:\Python\Python39\lib\site-packages\cefpython3" --lang=en-US --enable-media-stream --gpu-preferences=KAAAAAAAAACAAwCAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAKAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAQAAAAoAAAAQAAAAAAAAAAEAAAALAAAA --locales-dir-path="C:\Python\Python39\lib\site-packages\cefpython3\locales" --log-file="C:\Users\Andrew\debug.log" --log-severity=info --resources-dir-path="C:\Python\Python39\lib\site-packages\cefpython3" --lang=en-US /prefetch:2


DevTools listening on ws://127.0.0.1:49492/devtools/browser/40b4488f-43f4-4d79-9272-44051f9c2239

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by NiceneNerd** [comment]
Python 3.9 support on Windows is still hit-and-miss, try 3.8

**Comment by TheBaconGod** [comment]
I did that and it got it working thank you
