### ISSUE TITLE
bcml don't wan't to launch

### ISSUE THREAD

**Issue by Heliodore24** [NiceneNerd/BCML#446]
I have everythings needed installed, but every time i try to launch bcml, it never work
with the debug one, i get this :
<sub> Traceback (most recent call last):
  File "c:\users\theol\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\theol\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\theol\AppData\Local\Programs\Python\Python38\Scripts\bcml-debug.exe\__main__.py", line 4, in <module>
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 19, in <module>
    from bcml._api import Api
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 25, in <module>
    from bcml import DEBUG, install, dev, mergers, upgrade, util
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 25, in <module>
    from bcml import util, mergers, dev, upgrade
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\bcml\dev.py", line 18, in <module>
    from botw_havok import Havok
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\botw_havok\__init__.py", line 3, in <module>
    from .havok import Havok
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\botw_havok\havok.py", line 7, in <module>    import numpy as np
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\numpy\__init__.py", line 151, in <module>    from . import random
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\numpy\random\__init__.py", line 179, in <module>
    from . import _pickle
  File "c:\users\theol\appdata\local\programs\python\python38\lib\site-packages\numpy\random\_pickle.py", line 4, in <module>
    from ._sfc64 import SFC64
ImportError: DLL load failed while importing _sfc64: %1 n’est pas une application Win32 valide.</sub>
I have python 3.8 installed. I tried to uninstall it, then installing it again multiple time, i don't know what to try anymore.

**Comment by NiceneNerd** [comment]
I have no idea what that could possibly mean. Maybe `pip install --force-reinstall numpy`?

**Comment by Heliodore24** [comment]
Now i got that 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botw-havok 0.3.18 requires numpy~=1.19.2, but you have numpy 1.23.4 which is incompatible.
bcml 3.9.27 requires numpy==1.19.2; platform_system == "Windows", but you have numpy 1.23.4 which is incompatible.
Successfully installed numpy-1.23.4

**Comment by Heliodore24** [comment]
okay, i did `pip install --force-reinstall bcml` and it work again
