### ISSUE TITLE
python3.8.8 infinity install

### ISSUE THREAD

**Issue by ggtony233** [NiceneNerd/BCML#449]
```cmd
thread '<unnamed>' panicked at 'index out of bounds: the len is 3120 but the index is 18446744073709550810', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\yaz0-0.1.2\src\inflate.rs:71:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread Thread-33:
Traceback (most recent call last):
  File "a:\tool\ide\develop\python3.8.8\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "a:\tool\ide\develop\python3.8.8\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "a:\tool\ide\develop\python3.8.8\lib\site-packages\webview\util.py", line 138, in _call
    result = func(*func_params.values())
  File "a:\tool\ide\develop\python3.8.8\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "a:\tool\ide\develop\python3.8.8\lib\site-packages\bcml\install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "a:\tool\ide\develop\python3.8.8\lib\site-packages\bcml\_api.py", line 406, in install_mod
    install.refresh_merges()
  File "a:\tool\ide\develop\python3.8.8\lib\site-packages\bcml\install.py", line 602, in refresh_merges
    merger.perform_merge()
  File "a:\tool\ide\develop\python3.8.8\lib\site-packages\bcml\util.py", line 464, in timed_function
    res = func(*args, **kwargs)
  File "a:\tool\ide\develop\python3.8.8\lib\site-packages\bcml\mergers\pack.py", line 206, in perform_merge
    rsext.mergers.packs.merge_sarcs(sarcs)
pyo3_runtime.PanicException: index out of bounds: the len is 3120 but the index is 18446744073709550810
```
![](https://gitee.com/ggtony/images/raw/master/images/%E6%8D%95%E8%8E%B7.PNG)
Is there any way to fix this?

**Comment by GingerAvalanche** [comment]
Pretty sure there's a corrupt file somewhere. What mod are you trying to install?

**Comment by ggtony233** [comment]
linkle mod

**Comment by ggtony233** [comment]
I got it from Game Banana

**Comment by GingerAvalanche** [comment]
@ggtony233 Do you still have this error? I just noticed it's an error with yaz0, which means it's an error with one of the mod's files. It must not have been compressed correctly.

**Comment by ggtony233** [comment]
This mod has been out of updating for two years now。。。
