### ISSUE TITLE
BCML Mod Merging/Install Error

### ISSUE THREAD

**Issue by ReikoFox** [NiceneNerd/BCML#452]
This is what comes up and I'm just trying to install Zelda's Ballad.

Traceback (most recent call last):
  File "c:\users\project-elisse\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\project-elisse\appdata\local\programs\python\python38\lib\site-packages\bcml\_api.py", line 406, in install_mod
    install.refresh_merges()
  File "c:\users\project-elisse\appdata\local\programs\python\python38\lib\site-packages\bcml\install.py", line 602, in refresh_merges
    merger.perform_merge()
  File "c:\users\project-elisse\appdata\local\programs\python\python38\lib\site-packages\bcml\util.py", line 464, in timed_function
    res = func(*args, **kwargs)
  File "c:\users\project-elisse\appdata\local\programs\python\python38\lib\site-packages\bcml\mergers\texts.py", line 213, in perform_merge
    rsext.mergers.texts.merge_language(
RuntimeError: could not parse control sequences

Caused by:
    0: could not parse control sequence 5
    1: could not read field_2
    2: failed to fill whole buffer

I have no clue what to do.

**Comment by NiceneNerd** [comment]
One of the text files in the mod must be corrupt
