### ISSUE TITLE
Error while running webpack with Node `v18.12.1`: 'digital envelope routines'

### ISSUE THREAD

**Issue by jacobjmarks** [NiceneNerd/BCML#462]
When running `npm run build` (within `bcml/assets`) with Node `v18.12.1` the following output is observed:

```
> js@1.0.0 build
> webpack --mode production

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\jacob\source\BCML\bcml\assets\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\jacob\source\BCML\bcml\assets\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\jacob\source\BCML\bcml\assets\node_modules\webpack\lib\NormalModule.js:471:10)    at C:\Users\jacob\source\BCML\bcml\assets\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\jacob\source\BCML\bcml\assets\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\jacob\source\BCML\bcml\assets\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\jacob\source\BCML\bcml\assets\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\jacob\source\BCML\bcml\assets\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\jacob\source\BCML\bcml\assets\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\Users\jacob\source\BCML\bcml\assets\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\jacob\source\BCML\bcml\assets\node_modules\babel-loader\lib\index.js:55:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

The occurrence of this issue, based on the utilised LTS Node version, can be seen below:

| Node Version | Error Encountered? |
| - | - |
| `v18.12.1` | YES |
| `v16.18.1` | no |
| `v14.21.1` | no |

**Comment by jacobjmarks** [comment]
Looks like the root Issue and discussion is here: https://github.com/webpack/webpack/issues/14532
