### ISSUE TITLE
BCML doesn't open (cefpython3 doesn't support py310)

### ISSUE THREAD

**Issue by GingerAvalanche** [NiceneNerd/BCML#491]
Same issue, but I cannot launch via command line. 
```
c:\Users\Trevor\AppData\Local\Programs\Python\Python310\Scripts>py -m bcml
Traceback (most recent call last):
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python310\lib\site-packages\bcml\__main__.py", line 159, in <module>
    main()
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python310\lib\site-packages\bcml\__main__.py", line 93, in main
    import cefpython3
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python310\lib\site-packages\cefpython3\__init__.py", line 74, in <module>
    raise Exception("Python version not supported: " + sys.version)
Exception: Python version not supported: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
```

Looks like a python versioning issue...

_Originally posted by @tlf30 in https://github.com/NiceneNerd/BCML/issues/489#issuecomment-1404200258_

**Comment by GingerAvalanche** [comment]
Workarounds: Try uninstalling cefpython3 (`pip uninstall cefpython3`) to force it to use gtk (Linux) or edgechromium (Windows)

**Comment by GingerAvalanche** [comment]
Reopening until 3.10.6 can be released.

**Comment by GingerAvalanche** [comment]
3.10.6 release
