### ISSUE TITLE
RuntimeError: Failed to export merged mods

### ISSUE THREAD

**Issue by GreenFire010** [NiceneNerd/BCML#506]
When installing, merging or uninstalling following Error pops up:
Traceback (most recent call last):
File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/_api.py", line 33, in status_run
data = func(*args, **kwargs)
File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/install.py", line 265, in do_and_refresh
refresh_master_export()
File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/util.py", line 464, in timed_function
res = func(*args, **kwargs)
File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/install.py", line 274, in refresh_master_export
link_master_mod()
File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/install.py", line 745, in link_master_mod
rsext.manager.link_master_mod(str(output) if output else None)
RuntimeError: Failed to export merged mods

Caused by:
0: Failed to symlink output folder
1: No such file or directory (os error 2)

Using Miniconda3-py37_23.1.0-1-Linux-x86_64 (also tried using 3.8 phyton: same result)
from conda.io
and Cemu 1.27.1 installed via emudeck

Followed every step from CryoBytes33 Tutorial identically,but still no success. (https://youtu.be/WfAye3E-0nE)

Any ideas where to look or what to do?

**Comment by Zhawk1992** [comment]
I am getting the exact same errors as you after following CryoBytes33 tutorial. I'm unable to install any mod :(

**Comment by NiceneNerd** [comment]
For now just use the setting to disable links. It's not ideal, but Steam Deck is weird.

**Comment by Zhawk1992** [comment]
So I attempted that and was met with the following error -

Traceback (most recent call last):
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/install.py", line 319, in install_mod
    rules = json.loads((tmp_dir / "info.json").read_text("utf-8"))
  File "/home/deck/miniconda3/lib/python3.7/pathlib.py", line 1221, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/deck/miniconda3/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/home/deck/miniconda3/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpp5qoq8xx/info.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/_api.py", line 387, in install_mod
    for m in params["mods"]
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/_api.py", line 387, in <listcomp>
    for m in params["mods"]
  File "/home/deck/miniconda3/lib/python3.7/site-packages/bcml/install.py", line 375, in install_mod
    raise util.InstallError(err, name) from err
bcml.util.InstallError: An error occured when installing your mod, the name of which could not be detected. [Errno 2] No such file or directory: '/tmp/tmpp5qoq8xx/info.json'
Your mod is being removed, and no changes have been made.

**Comment by NiceneNerd** [comment]
That's probably related to a new, recent issue. What BCML version are you on?

**Comment by Zhawk1992** [comment]
3.10.7

**Comment by GingerAvalanche** [comment]
Fixed in 3.10.8
