### ISSUE TITLE
Unable to load DLL 'WebView2Loader.dll'

### ISSUE THREAD

**Issue by mja00** [NiceneNerd/BCML#507]
Currently trying to use BCML on Windows 11. Installed through pip and whenever I run the program I get the following error:
```
[pywebview] WebView2 initialization failed with exception:
 Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: The specified module could not be found (0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()
   ```
   I tried everything. Please help!

**Comment by mja00** [comment]
I installed Python 3.9 and it started working lol
