### ISSUE TITLE
Installing .bnp file causes an error that doesn't allow the install to proceed.

### ISSUE THREAD

**Issue by joe-f-dev** [NiceneNerd/BCML#509]
- BCML v3.10.8
- Python v3.9
- Windows 10 Pro (64-bit)
- Intel i5 12600k
- AMD Radeon 6900XT

Attempting to install older .bnp files results in an error, installed a .zip file just fine however. 

For example, trying to install "wildrunning_25.bnp" results in this error message:

> "Oops! An error occured when installing your mod. 'Definition' Your mod is being removed, and no changes have been made."

```
Traceback (most recent call last):
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 295, in install_mod
    tmp_dir = open_mod(mod)
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 122, in open_mod
    upgrade.convert_old_mod(rulesdir, delete_old=True)
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\upgrade.py", line 38, in convert_old_mod
    info = parse_rules(mod / "rules.txt")
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\upgrade.py", line 74, in parse_rules
    "name": str(rules["Definition"]["name"]).strip("\"' "),
  File "c:\users\joe\appdata\local\programs\python\python39\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Definition'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 380, in install_mod
    mods = [
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 381, in <listcomp>
    install.install_mod(
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 312, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. 'Definition'
Your mod is being removed, and no changes have been made.
```

A similar error appears when attempting to update these .bnps

As a troubleshooting step I backed up my mod list and uninstalled everything. This did not resolve the issue. When I attempted to restore the mod list it failed giving this error:

```
Traceback (most recent call last):
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\_api.py", line 569, in restore_backup
    install.restore_backup(params["backup"])
  File "c:\users\joe\appdata\local\programs\python\python39\lib\site-packages\bcml\install.py", line 645, in restore_backup
    subprocess.run(
  File "c:\users\joe\appdata\local\programs\python\python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Joe\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\bcml\\helpers\\7z.exe', 'x', 'C:\\Users\\Joe\\AppData\\Local\\bcml\\backups\\Issue_Definition---7.7z', '-oC:\\Users\\Joe\\AppData\\Local\\bcml\\mods']' returned non-zero exit status 255.
```

**Comment by GingerAvalanche** [comment]
The first error comes from an incorrectly-made rules.txt file - which is what both cemu and bcml use to determine what the mod's name and description are. Making a proper one, or fixing the one it has so that the first line says `[Definition]`, should fix that.

Second error is some generic 7zip extraction failure. Code 255 tells us nothing, but unfortunately that's all it gives us. You can manually restore your mod list by clearing out `C:\\Users\\Joe\\AppData\\Local\\bcml\\mods`, then extracting the backup there, reopening bcml, and hitting the remerge button.

**Comment by rehtlaw** [comment]
I do get the `Definition` error myself too. All the mods that result in that error have installed perfectly fine in the past and I've checked their `rules.txt` files if the first line is correct.

**Comment by NiceneNerd** [comment]
I'm fairly certain it's caused by attempting to read the `rules.txt` after the converter has already replaced it with the `info.json`, leaving an empty stream.

**Comment by koshisan** [comment]
https://www.reddit.com/r/CemuPiracy/comments/11l2hx0/comment/jbzr3ni/

Has the format changed recently? Older versions of BCML seem to install the mods just fine...

**Comment by NiceneNerd** [comment]
It dropped support for BCML 2 BNPs
