### ISSUE TITLE
urllib3

### ISSUE THREAD

**Issue by MTFChrono** [NiceneNerd/BCML#51]
i downloaded the latest ver and it showed this on the log file
Traceback (most recent call last):
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\BCML.launch.pyw", line 34, in <module>
    from bcml.__main__ import main
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\pkgs\bcml\__main__.py", line 20, in <module>
    from bcml import DEBUG, NO_CEF, install, dev, mergers, upgrade, util, _oneclick
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\pkgs\bcml\_oneclick.py", line 2, in <module>
    import requests
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\pkgs\requests\__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

**Comment by NiceneNerd** [comment]
Hm, dumb dependency issues. Open a command prompt or PowerShell window to `C:\Users\NIGGA\Downloads\Easeus 14 02_47\` and run `Python\python.exe -m pip install urllib3`

**Comment by MTFChrono** [comment]
doing that got me this
```
Collecting urllib3
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 819 kB/s
ERROR: requests 2.23.0 requires certifi>=2017.4.17, which is not installed.
ERROR: requests 2.23.0 requires chardet<4,>=3.0.2, which is not installed.
ERROR: requests 2.23.0 requires idna<3,>=2.5, which is not installed.
Installing collected packages: urllib3
Successfully installed urllib3-1.25.9
```

**Comment by MTFChrono** [comment]
and now this when i run bcml
`Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\bin\bcml.exe\__main__.py", line 17, in <module>
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\pkgs\bcml\__main__.py", line 20, in <module>
    from bcml import DEBUG, NO_CEF, install, dev, mergers, upgrade, util, _oneclick
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\pkgs\bcml\_oneclick.py", line 2, in <module>
    import requests
  File "C:\Users\NIGGA\Downloads\Easeus 14 02_47\pkgs\requests\__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'`

**Comment by NiceneNerd** [comment]
Do the same, but this time for `chardet` instead of `urllib3`

**Comment by MTFChrono** [comment]
yooooooo after installing all that jazz in the errors, it works! thanks my guy
