### ISSUE TITLE
Can't install mods (Fedora 37)

### ISSUE THREAD

**Issue by headkittens** [NiceneNerd/BCML#511]
Fedora 37
AMD Ryzen 3600
AMD Radeon 580
Python 3.11, 3.10 and 3.9 (in the posted error in a virtual environment, 3.10)

BCML installed via pip in each case and it seems to work fine aside from installing or preparing any mods for installation.

I don't know what to say, I've done everything I can, I've redownloaded the mods, I've tried multiple mods, I can't point it to a CEMU directory, because `~/.config/Cemu` where `settings.xml` is doesn't seem to matter and I'm running it from the AppImage.

Initially I had the game on another EXT4 formatted SSD, but even bringing it to my home directory makes no difference.

I'm not a Linux newbie, but I'm also not an expert, so I genuinely don't know how to resolve this at all.

At the moment I've just taken the BCML graphics pack I generated from Windows and that works fine, but it's also old, so I can't try Linkle 3.0. I also don't have access to Windows anymore, because I fucking hate it and removed every trace of it today from my computer.

```
Traceback (most recent call last):
  File "/home/phoebe/pythonbullshit/.venv/lib64/python3.10/site-packages/bcml/install.py", line 295, in install_mod
    tmp_dir = open_mod(mod)
  File "/home/phoebe/pythonbullshit/.venv/lib64/python3.10/site-packages/bcml/install.py", line 99, in open_mod
    raise Exception(
Exception: No files were extracted. This may be because of an invalid or corrupted download.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/phoebe/pythonbullshit/.venv/lib64/python3.10/site-packages/bcml/_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "/home/phoebe/pythonbullshit/.venv/lib64/python3.10/site-packages/bcml/install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "/home/phoebe/pythonbullshit/.venv/lib64/python3.10/site-packages/bcml/_api.py", line 380, in install_mod
    mods = [
  File "/home/phoebe/pythonbullshit/.venv/lib64/python3.10/site-packages/bcml/_api.py", line 381, in <listcomp>
    install.install_mod(
  File "/home/phoebe/pythonbullshit/.venv/lib64/python3.10/site-packages/bcml/install.py", line 312, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. No files were extracted. This may be because of an invalid or corrupted download.
Your mod is being removed, and no changes have been made.
```

_EDIT: I just tried deleting all the BCML configurations and starting from scratch, I get an empty error message when attempting to save settings for creating without CEMU install, then it allows me to continue to use BCML, but still cannot install mods_

Any ideas?

**Comment by NiceneNerd** [comment]
For that particular error, try toggling the bundled 7z setting

**Comment by headkittens** [comment]
Actually, I just found out you made UKMM and that one is much more pick up and use, got a few quirks, but I much prefer it, thank you so much!
