### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by thiccjak** [NiceneNerd/BCML#523]
Tried opening BCML, white screen. Tried the debug and it has a white screen. The debug opened with this cmd that says this.

 Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: The specified module could not be found (0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()

**Comment by GingerAvalanche** [comment]
See https://github.com/NiceneNerd/BCML/issues/508
