### ISSUE TITLE
'TextureRedefine' already exists error when installing mods

### ISSUE THREAD

**Issue by jclsn** [NiceneNerd/BCML#525]
I am getting this error when trying to install mods. How to fix this? Is the Python version not compatible? I am on Linux and chose the "without Cemu directory" setting. I have created a directory for merged exports.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bcml/upgrade.py", line 36, in convert_old_mod
    rules_to_info(mod / "rules.txt", delete_old=delete_old)
  File "/usr/lib/python3.10/site-packages/bcml/upgrade.py", line 95, in rules_to_info
    info = parse_rules(rules_path)
  File "/usr/lib/python3.10/site-packages/bcml/upgrade.py", line 72, in parse_rules
    rules.read(str(rules_path))
  File "/usr/lib/python3.10/configparser.py", line 699, in read
    self._read(fp, filename)
  File "/usr/lib/python3.10/configparser.py", line 1072, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from '/tmp/tmp789vd15o/rules.txt' [line 15]: section 'TextureRedefine' already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bcml/_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/bcml/install.py", line 264, in do_and_refresh
    res = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/bcml/_api.py", line 380, in install_mod
    mods = [
  File "/usr/lib/python3.10/site-packages/bcml/_api.py", line 381, in <listcomp>
    install.install_mod(
  File "/usr/lib/python3.10/site-packages/bcml/install.py", line 312, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. While reading from '/tmp/tmp789vd15o/rules.txt' [line 15]: section 'TextureRedefine' already exists
Your mod is being removed, and no changes have been made.
```

**Comment by NiceneNerd** [comment]
What mod are you installing? This looks like it's probably not a supported mod format

**Comment by jclsn** [comment]
It was the Clarity FX mode, but I just found out that Cemu already can load mods and I don't need this tool anymore.

**Comment by NiceneNerd** [comment]
@jclsn I think you're confused. Clarity is a purely visual, shader-based graphic pack. BCML is for game ROM file replacement mods, which need to be merged together to use more than one of them.

**Comment by jclsn** [comment]
Ah okay, thanks for clarifying
