### ISSUE TITLE
Crashing when exporting

### ISSUE THREAD

**Issue by micah686** [NiceneNerd/BCML#65]
When running in switch mode, and I try to export the mods, I get the following error:

Oops! Command '['E:\\Program Files\\BCML\\pkgs\\bcml\\helpers\\7z.exe', 'a', 'C:\\Users\\Guest\\Downloads\\botw\\exported-mods.zip', 'E:tmp_bcml_export\\*']' returned non-zero exit status 1.

```
Traceback (most recent call last):
  File "E:\Program Files\BCML\pkgs\bcml\_api.py", line 44, in status_run
    func(*args, **kwargs)
  File "E:\Program Files\BCML\pkgs\bcml\_api.py", line 461, in export
    install.export(output)
  File "E:\Program Files\BCML\pkgs\bcml\install.py", line 716, in export
    check=True,
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['E:\\Program Files\\BCML\\pkgs\\bcml\\helpers\\7z.exe', 'a', 'C:\\Users\\Guest\\Downloads\\botw\\exported-mods.zip', 'E:tmp_bcml_export\\*']' returned non-zero exit status 1.
```
I don't have a D:\obj\ directory, if that makes any difference.

for the base game directory, I am using the game with the 1.6 update. Should I not be doing that?

I tried this on the BCML_3.0.0rc1 AND BCML_3.0.0rc2.

I also tried a few different BNP files, including a few I self made, as well as some from online.

**Comment by micah686** [comment]
Fixed with RC 3
