### ISSUE TITLE
v3 Error writing to files

### ISSUE THREAD

**Issue by axfty** [NiceneNerd/BCML#71]
I tried out v3.0, and I keep running into errors after installing more than one mod. It always seems to be an issue with being unable to edit bootup,pack. Specifically:
```
[WinError 183] Cannot create a file when that file already exists: 'F:\\Games\\Emulators\\WII U\\BCML 3.0\\data\\mods\\9999_BCML\\content\\Pack\\Bootup.pack' Note that this could leave your game in an unplayable state.
```

```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pathlib.py", line 1268, in mkdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\Games\\Emulators\\WII U\\CEMU\\graphicPacks\\BreathOfTheWild_BCML\\content\\Pack\\Bootup.pack\\Actor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Games\Emulators\WII U\BCML 3.0\pkgs\bcml\_api.py", line 325, in apply_queue
    install.refresh_master_export()
  File "F:\Games\Emulators\WII U\BCML 3.0\pkgs\bcml\install.py", line 267, in refresh_master_export
    link_master_mod()
  File "F:\Games\Emulators\WII U\BCML 3.0\pkgs\bcml\install.py", line 666, in link_master_mod
    (output / rel_path).mkdir(parents=True, exist_ok=True)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pathlib.py", line 1272, in mkdir
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pathlib.py", line 1268, in mkdir
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'F:\\Games\\Emulators\\WII U\\CEMU\\graphicPacks\\BreathOfTheWild_BCML\\content\\Pack\\Bootup.pack'
```

**Comment by NiceneNerd** [comment]
I'm not really sure how that can be happening when the code explicitly says to ignore this kind of error. I've also never seen it before.

**Comment by NiceneNerd** [comment]
You can see that the line reference in the error explicitly allows for the file or folder to already exist: `(output / rel_path).mkdir(parents=True, exist_ok=True)`

**Comment by NiceneNerd** [comment]
What mod(s) are you trying to use?

**Comment by NiceneNerd** [comment]
Unable to reproduce, but added some possible error catching code in 4e533da0f8d5d4d324eb5d7cd8210c6bfba48c63.
