### ISSUE TITLE
(rc7-3.0.5+?) Invalid Requirement Error When Updating

### ISSUE THREAD

**Issue by SkyNinja** [NiceneNerd/BCML#80]
Version: BCML 3.0rc7 - 3.0.5, most likely also 3.0.6
OS: Windows 10 pro

When trying to use BCML's built-in updater, I get this error message:

```
Traceback (most recent call last):
  File "C:\BCML\pkgs\bcml\_api.py", line 44, in status_run
  File "C:\BCML\pkgs\bcml\_api.py", line 677, in update_bcml
RuntimeError: ERROR: Invalid requirement: ''
```

After getting this error in rc7, I installed 3.0.5 over my rc7 install and tried again, to see if the updater changes had fixed it. Unfortunately, I got the error again. The error above is copied from that attempt.

Upon updating to 3.0.6 via the installer, clicking the check for updates button immediately prompts me that "BCML has been successfully updated," and pressing the restart button closes the software entirely.

**Comment by NiceneNerd** [comment]
I've been investigating this to no avail so far. Still trying to find a cause.

**Comment by NiceneNerd** [comment]
This might be fixed as of v3.0.7, if someone can confirm with the 3.0.8 update.

**Comment by SkyNinja** [comment]
It did update correctly, though when I let it restart, I got this error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\BCML\Python\lib\site-packages\bcml\_oneclick.py", line 17, in listen
    sock.bind(("127.0.0.1", 6666))
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 926, in _bootstrap_inner
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\threading.py", line 870, in run
  File "C:\BCML\Python\lib\site-packages\bcml\_oneclick.py", line 19, in listen
    send_arg(sock)
  File "C:\BCML\Python\lib\site-packages\bcml\_oneclick.py", line 37, in send_arg
    sock.sendall(sys.argv[1].encode("utf8"))
IndexError: list index out of range

```

Maybe the old instance hadn't closed before the new one was launched?

**Comment by NiceneNerd** [comment]
Yeah, that can happen after update. So far I haven't found a reliable way to time the relaunch to make sure it clears. Either way, it can be relaunched manually afterwards.
