### ISSUE TITLE
Unable to export on linux

### ISSUE THREAD

**Issue by Lillievela** [NiceneNerd/BCML#84]
Managed to get everything working (aside from some gtk errors and a few crashes that dont seem to have a clear cause) and I cannot seem to figure out why it isnt exporting, i can remerge but attempting to export gives me this error
`Traceback (most recent call last):
  File "/home/lillie/.local/lib/python3.8/site-packages/bcml/_api.py", line 44, in status_run
    data = func(*args, **kwargs)
  File "/home/lillie/.local/lib/python3.8/site-packages/bcml/_api.py", line 496, in export
    install.export(output)
  File "/home/lillie/.local/lib/python3.8/site-packages/bcml/install.py", line 751, in export
    result = subprocess.run(check=False, capture_output=True)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() missing 1 required positional argument: 'args'

`

**Comment by NiceneNerd** [comment]
Fixed in 75a92060bddcc0e3b350dd1d58a3bbdd2ffa707f
