### ISSUE TITLE
MamonoShop error

### ISSUE THREAD

**Issue by MTFChrono** [NiceneNerd/BCML#85]
Hi! I was just trying to remerge my mods when suddenly, I met this error. I also don't know if this is the root cause of my game being stuck on the save loading screen. Thanks in advance!

```
multiprocessing.pool.RemoteTraceback:` 
"""
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 121, in worker
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 44, in mapstar
  File "C:\Users\NIGGA\Downloads\Games\The Legend of Zelda - Breath of the Wild\pkgs\bcml\mergers\shop.py", line 277, in threaded_merge
    raise ValueError(f"{file} is not a SARC or AAMP file.")
ValueError: content/Actor/Pack/Npc_MamonoShop.sbactorpack is not a SARC or AAMP file.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\NIGGA\Downloads\Games\The Legend of Zelda - Breath of the Wild\pkgs\bcml\install.py", line 582, in uninstall_mod
    refresh_merges()
  File "C:\Users\NIGGA\Downloads\Games\The Legend of Zelda - Breath of the Wild\pkgs\bcml\install.py", line 596, in refresh_merges
    merger.perform_merge()
  File "C:\Users\NIGGA\Downloads\Games\The Legend of Zelda - Breath of the Wild\pkgs\bcml\mergers\shop.py", line 402, in perform_merge
    pool.map(partial(threaded_merge), diffs.items())
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 268, in map
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pool.py", line 657, in get
ValueError: content/Actor/Pack/Npc_MamonoShop.sbactorpack is not a SARC or AAMP file.
``
```

**Comment by NiceneNerd** [comment]
This is a problem with one of your mods, not BCML. Whichever one contains `Npc_MamonoShop.sbactorpack`.
