### ISSUE TITLE
Rar loading 

### ISSUE THREAD

**Issue by LisandraBrave** [NiceneNerd/BCML#87]
Any mod in a rar file fails to install, with the error 
```
Traceback (most recent call last):
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/install.py", line 334, in install_mod
    tmp_dir = open_mod(mod)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/install.py", line 68, in open_mod
    raise Exception("No files were extracted.")
Exception: No files were extracted.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/_api.py", line 49, in status_run
    data = func(*args, **kwargs)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/install.py", line 262, in do_and_refresh
    res = func(*args, **kwargs)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/_api.py", line 268, in install_mod
    mods = [
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/_api.py", line 269, in <listcomp>
    install.install_mod(
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/install.py", line 351, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. No files were extracted.
Your mod is being removed, and no changes have been made.
```
The same mod manually unpacked and loaded through rules.txt functions as expected. bnp mods load as expected

```
$ uname -r
5.8.16-200.fc32.x86_64
$ python --version
Python 3.8.6
$ pip show bcml
Name: bcml
Version: 3.1.0
```

**Comment by NiceneNerd** [comment]
Does your system have 7z installed itself? If so, does that copy work on RAR files?

**Comment by LisandraBrave** [comment]
Yes, and no respectively. RAR support was removed from fedora's provided 7z due to it having a non-free license. I do have `unrar` available for handling RAR archives.

**Comment by NiceneNerd** [comment]
Hmm, BCML is set to use the system 7z for all archives if available. Can you check if executing the copy included with BCML (should be `/home/lis/.local/lib/python3.8/site-packages/bcml/helpers/7z`) works properly? If so I'll add an option to force the bundled version.

**Comment by LisandraBrave** [comment]
Running `.../bcml/helpers/7z l <rar file>` lists the contents of the archive, whereas `7z l <rar file>` does not, so yes, it seems to work properly.

**Comment by NiceneNerd** [comment]
New option added in 3.1.1.

**Comment by LisandraBrave** [comment]
Error persists on 3.1.1 after ensuring update with `$ pip install bcml --user --force-reinstall --pre --no-cache-dir`
Menu option does not appear, and setting `force_7z` manually in settings.json causes
```
Traceback (most recent call last):
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/install.py", line 87, in open_mod
    upgrade.convert_old_mod(rulesdir, delete_old=True)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/upgrade.py", line 44, in convert_old_mod
    rules_to_info(mod / "rules.txt", delete_old=delete_old)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/upgrade.py", line 101, in rules_to_info
    info = parse_rules(rules_path)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/upgrade.py", line 81, in parse_rules
    "name": str(rules["Definition"]["name"]).strip("\"' "),
  File "/usr/lib64/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Definition'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/_api.py", line 49, in status_run
    data = func(*args, **kwargs)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/install.py", line 262, in do_and_refresh
    res = func(*args, **kwargs)
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/_api.py", line 270, in install_mod
    mods = [
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/_api.py", line 271, in <listcomp>
    install.install_mod(
  File "/home/lis/.local/lib/python3.8/site-packages/bcml/install.py", line 351, in install_mod
    raise util.InstallError(err) from err
bcml.util.InstallError: An error occured when installing your mod. 'Definition'
Your mod is being removed, and no changes have been made.
```

```
$ pip show bcml
Name: bcml
Version: 3.1.1
```

**Comment by NiceneNerd** [comment]
If the menu option doesn't appear, what happens if you run with `bcml-debug`, open developer tools, and grab the value of `window.navigator.platform`?

**Comment by LisandraBrave** [comment]
```
> window.navigator.platform
< "Linux x86_64"
```

**Comment by NiceneNerd** [comment]
Ooh, wait a second. I think I accidentally left the condition for showing the setting inverted from testing on Windows. Darn silly me.
